<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 6 Basic Quantitative Geography  | Spatial Analysis with R</title>
  <meta name="description" content="A bookdown book on how to conduct spatial analysis with R." />
  <meta name="generator" content="bookdown 0.25 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 6 Basic Quantitative Geography  | Spatial Analysis with R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="A bookdown book on how to conduct spatial analysis with R." />
  <meta name="github-repo" content="ChiaJung-Yeh/Spatial-Analysis" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 6 Basic Quantitative Geography  | Spatial Analysis with R" />
  
  <meta name="twitter:description" content="A bookdown book on how to conduct spatial analysis with R." />
  

<meta name="author" content="Chia Jung, Yeh National Yang Ming Chiao Tung University (NYCU), Taiwan" />


<meta name="date" content="2022-04-16" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="spatial-operations.html"/>

<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="lib/css/bootstrap.min.css" type="text/css" />
<link rel="stylesheet" href="lib/css/style.css" type="text/css" />
<link rel="stylesheet" href="lib/css/lesson.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Spatial Analysis with R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> <strong>Introduction</strong><span></span></a></li>
<li class="chapter" data-level="2" data-path="basic-knowledge-on-gis.html"><a href="basic-knowledge-on-gis.html"><i class="fa fa-check"></i><b>2</b> <strong>Basic Knowledge on GIS</strong><span></span></a>
<ul>
<li class="chapter" data-level="2.1" data-path="basic-knowledge-on-gis.html"><a href="basic-knowledge-on-gis.html#geographic-information-systems"><i class="fa fa-check"></i><b>2.1</b> Geographic Information Systems<span></span></a></li>
<li class="chapter" data-level="2.2" data-path="basic-knowledge-on-gis.html"><a href="basic-knowledge-on-gis.html#well-known-text-wkt"><i class="fa fa-check"></i><b>2.2</b> Well-Known Text (WKT)<span></span></a></li>
<li class="chapter" data-level="2.3" data-path="basic-knowledge-on-gis.html"><a href="basic-knowledge-on-gis.html#shapefile"><i class="fa fa-check"></i><b>2.3</b> Shapefile<span></span></a></li>
<li class="chapter" data-level="2.4" data-path="basic-knowledge-on-gis.html"><a href="basic-knowledge-on-gis.html#coordinate-reference-system-crs"><i class="fa fa-check"></i><b>2.4</b> Coordinate Reference System (CRS)<span></span></a></li>
<li class="chapter" data-level="2.5" data-path="basic-knowledge-on-gis.html"><a href="basic-knowledge-on-gis.html#why-use-r"><i class="fa fa-check"></i><b>2.5</b> Why Use R?<span></span></a></li>
<li class="chapter" data-level="2.6" data-path="basic-knowledge-on-gis.html"><a href="basic-knowledge-on-gis.html#required-packages"><i class="fa fa-check"></i><b>2.6</b> Required Packages<span></span></a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="data-visualization-with-maps.html"><a href="data-visualization-with-maps.html"><i class="fa fa-check"></i><b>3</b> <strong>Data Visualization with Maps</strong><span></span></a>
<ul>
<li class="chapter" data-level="3.1" data-path="data-visualization-with-maps.html"><a href="data-visualization-with-maps.html#making-maps"><i class="fa fa-check"></i><b>3.1</b> Making Maps<span></span></a></li>
<li class="chapter" data-level="3.2" data-path="data-visualization-with-maps.html"><a href="data-visualization-with-maps.html#attributes-of-shapefile"><i class="fa fa-check"></i><b>3.2</b> Attributes of Shapefile<span></span></a></li>
<li class="chapter" data-level="3.3" data-path="data-visualization-with-maps.html"><a href="data-visualization-with-maps.html#labels-on-map"><i class="fa fa-check"></i><b>3.3</b> Labels on Map<span></span></a></li>
<li class="chapter" data-level="3.4" data-path="data-visualization-with-maps.html"><a href="data-visualization-with-maps.html#graduated-symbol-map"><i class="fa fa-check"></i><b>3.4</b> Graduated Symbol Map<span></span></a></li>
<li class="chapter" data-level="3.5" data-path="data-visualization-with-maps.html"><a href="data-visualization-with-maps.html#categorized-symbol-map"><i class="fa fa-check"></i><b>3.5</b> Categorized Symbol Map<span></span></a></li>
<li class="chapter" data-level="3.6" data-path="data-visualization-with-maps.html"><a href="data-visualization-with-maps.html#rule-based-symbol-map"><i class="fa fa-check"></i><b>3.6</b> Rule-based Symbol Map<span></span></a></li>
<li class="chapter" data-level="3.7" data-path="data-visualization-with-maps.html"><a href="data-visualization-with-maps.html#basic-operationselements-of-map"><i class="fa fa-check"></i><b>3.7</b> Basic Operations/Elements of Map<span></span></a>
<ul>
<li class="chapter" data-level="3.7.1" data-path="data-visualization-with-maps.html"><a href="data-visualization-with-maps.html#map-overlay"><i class="fa fa-check"></i><b>3.7.1</b> <strong>Map Overlay</strong><span></span></a></li>
<li class="chapter" data-level="3.7.2" data-path="data-visualization-with-maps.html"><a href="data-visualization-with-maps.html#north-arrow-and-scale"><i class="fa fa-check"></i><b>3.7.2</b> <strong>North Arrow and Scale</strong><span></span></a></li>
<li class="chapter" data-level="3.7.3" data-path="data-visualization-with-maps.html"><a href="data-visualization-with-maps.html#linetypeshape"><i class="fa fa-check"></i><b>3.7.3</b> <strong>Linetype/Shape</strong><span></span></a></li>
<li class="chapter" data-level="3.7.4" data-path="data-visualization-with-maps.html"><a href="data-visualization-with-maps.html#theme"><i class="fa fa-check"></i><b>3.7.4</b> <strong>Theme</strong><span></span></a></li>
</ul></li>
<li class="chapter" data-level="3.8" data-path="data-visualization-with-maps.html"><a href="data-visualization-with-maps.html#other-mapping-tools"><i class="fa fa-check"></i><b>3.8</b> Other Mapping Tools<span></span></a>
<ul>
<li class="chapter" data-level="3.8.1" data-path="data-visualization-with-maps.html"><a href="data-visualization-with-maps.html#tmap"><i class="fa fa-check"></i><b>3.8.1</b> <strong>tmap</strong><span></span></a></li>
<li class="chapter" data-level="3.8.2" data-path="data-visualization-with-maps.html"><a href="data-visualization-with-maps.html#leaflet"><i class="fa fa-check"></i><b>3.8.2</b> <strong>leaflet</strong><span></span></a></li>
</ul></li>
<li class="chapter" data-level="3.9" data-path="data-visualization-with-maps.html"><a href="data-visualization-with-maps.html#practice"><i class="fa fa-check"></i><b>3.9</b> <span style="border-bottom: 3px double black"><em><em>PRACTICE</em></em></span><span></span></a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="geographic-data.html"><a href="geographic-data.html"><i class="fa fa-check"></i><b>4</b> <strong>Geographic Data</strong><span></span></a>
<ul>
<li class="chapter" data-level="4.1" data-path="geographic-data.html"><a href="geographic-data.html#simple-feature-geometries-sfg"><i class="fa fa-check"></i><b>4.1</b> Simple Feature Geometries (sfg)<span></span></a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="geographic-data.html"><a href="geographic-data.html#point"><i class="fa fa-check"></i><b>4.1.1</b> <strong>Point</strong><span></span></a></li>
<li class="chapter" data-level="4.1.2" data-path="geographic-data.html"><a href="geographic-data.html#linestring"><i class="fa fa-check"></i><b>4.1.2</b> <strong>Linestring</strong><span></span></a></li>
<li class="chapter" data-level="4.1.3" data-path="geographic-data.html"><a href="geographic-data.html#polygon"><i class="fa fa-check"></i><b>4.1.3</b> <strong>Polygon</strong><span></span></a></li>
<li class="chapter" data-level="4.1.4" data-path="geographic-data.html"><a href="geographic-data.html#multipoint"><i class="fa fa-check"></i><b>4.1.4</b> <strong>Multipoint</strong><span></span></a></li>
<li class="chapter" data-level="4.1.5" data-path="geographic-data.html"><a href="geographic-data.html#multilinestring"><i class="fa fa-check"></i><b>4.1.5</b> <strong>Multilinestring</strong><span></span></a></li>
<li class="chapter" data-level="4.1.6" data-path="geographic-data.html"><a href="geographic-data.html#multipolygon"><i class="fa fa-check"></i><b>4.1.6</b> <strong>Multipolygon</strong><span></span></a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="geographic-data.html"><a href="geographic-data.html#simple-feature-columns-sfc"><i class="fa fa-check"></i><b>4.2</b> Simple Feature Columns (sfc)<span></span></a></li>
<li class="chapter" data-level="4.3" data-path="geographic-data.html"><a href="geographic-data.html#simple-feature-sf"><i class="fa fa-check"></i><b>4.3</b> Simple Feature (sf)<span></span></a></li>
<li class="chapter" data-level="4.4" data-path="geographic-data.html"><a href="geographic-data.html#convert-text-file-to-shapefile"><i class="fa fa-check"></i><b>4.4</b> Convert Text File to Shapefile<span></span></a></li>
<li class="chapter" data-level="4.5" data-path="geographic-data.html"><a href="geographic-data.html#reproject-geographic-data"><i class="fa fa-check"></i><b>4.5</b> Reproject Geographic Data<span></span></a></li>
<li class="chapter" data-level="4.6" data-path="geographic-data.html"><a href="geographic-data.html#geographic-data-export"><i class="fa fa-check"></i><b>4.6</b> Geographic Data Export<span></span></a></li>
<li class="chapter" data-level="4.7" data-path="geographic-data.html"><a href="geographic-data.html#geographic-data-format"><i class="fa fa-check"></i><b>4.7</b> Geographic Data Format<span></span></a></li>
<li class="chapter" data-level="4.8" data-path="geographic-data.html"><a href="geographic-data.html#join-attribute-and-spatial-data"><i class="fa fa-check"></i><b>4.8</b> Join Attribute and Spatial Data<span></span></a></li>
<li class="chapter" data-level="4.9" data-path="geographic-data.html"><a href="geographic-data.html#practice-1"><i class="fa fa-check"></i><b>4.9</b> <span style="border-bottom: 3px double black"><em><em>PRACTICE</em></em></span><span></span></a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="spatial-operations.html"><a href="spatial-operations.html"><i class="fa fa-check"></i><b>5</b> <strong>Spatial Operations</strong><span></span></a>
<ul>
<li class="chapter" data-level="5.1" data-path="spatial-operations.html"><a href="spatial-operations.html#spatial-join"><i class="fa fa-check"></i><b>5.1</b> Spatial Join<span></span></a></li>
<li class="chapter" data-level="5.2" data-path="spatial-operations.html"><a href="spatial-operations.html#attribute-aggregation"><i class="fa fa-check"></i><b>5.2</b> Attribute Aggregation<span></span></a></li>
<li class="chapter" data-level="5.3" data-path="spatial-operations.html"><a href="spatial-operations.html#spatial-aggregation"><i class="fa fa-check"></i><b>5.3</b> Spatial Aggregation<span></span></a></li>
<li class="chapter" data-level="5.4" data-path="spatial-operations.html"><a href="spatial-operations.html#interpolation"><i class="fa fa-check"></i><b>5.4</b> Interpolation<span></span></a></li>
<li class="chapter" data-level="5.5" data-path="spatial-operations.html"><a href="spatial-operations.html#unions"><i class="fa fa-check"></i><b>5.5</b> Unions<span></span></a></li>
<li class="chapter" data-level="5.6" data-path="spatial-operations.html"><a href="spatial-operations.html#centroid"><i class="fa fa-check"></i><b>5.6</b> Centroid<span></span></a></li>
<li class="chapter" data-level="5.7" data-path="spatial-operations.html"><a href="spatial-operations.html#buffer"><i class="fa fa-check"></i><b>5.7</b> Buffer<span></span></a></li>
<li class="chapter" data-level="5.8" data-path="spatial-operations.html"><a href="spatial-operations.html#boundary"><i class="fa fa-check"></i><b>5.8</b> Boundary<span></span></a></li>
<li class="chapter" data-level="5.9" data-path="spatial-operations.html"><a href="spatial-operations.html#clipping"><i class="fa fa-check"></i><b>5.9</b> Clipping<span></span></a></li>
<li class="chapter" data-level="5.10" data-path="spatial-operations.html"><a href="spatial-operations.html#simplification"><i class="fa fa-check"></i><b>5.10</b> Simplification<span></span></a></li>
<li class="chapter" data-level="5.11" data-path="spatial-operations.html"><a href="spatial-operations.html#affine-transformations"><i class="fa fa-check"></i><b>5.11</b> Affine Transformations<span></span></a></li>
<li class="chapter" data-level="5.12" data-path="spatial-operations.html"><a href="spatial-operations.html#geometric-measurement"><i class="fa fa-check"></i><b>5.12</b> Geometric Measurement<span></span></a></li>
<li class="chapter" data-level="5.13" data-path="spatial-operations.html"><a href="spatial-operations.html#nearest-analysis"><i class="fa fa-check"></i><b>5.13</b> Nearest Analysis<span></span></a></li>
<li class="chapter" data-level="5.14" data-path="spatial-operations.html"><a href="spatial-operations.html#convex-hull"><i class="fa fa-check"></i><b>5.14</b> Convex Hull<span></span></a></li>
<li class="chapter" data-level="5.15" data-path="spatial-operations.html"><a href="spatial-operations.html#voronoi-polygon"><i class="fa fa-check"></i><b>5.15</b> Voronoi Polygon<span></span></a></li>
<li class="chapter" data-level="5.16" data-path="spatial-operations.html"><a href="spatial-operations.html#practice-2"><i class="fa fa-check"></i><b>5.16</b> <span style="border-bottom: 3px double black"><em><em>PRACTICE</em></em></span><span></span></a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="basic-quantitative-geography.html"><a href="basic-quantitative-geography.html"><i class="fa fa-check"></i><b>6</b> <strong>Basic Quantitative Geography </strong><span></span></a>
<ul>
<li class="chapter" data-level="6.1" data-path="basic-quantitative-geography.html"><a href="basic-quantitative-geography.html#point-patterns-analysis"><i class="fa fa-check"></i><b>6.1</b> Point Patterns Analysis<span></span></a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="basic-quantitative-geography.html"><a href="basic-quantitative-geography.html#basic-measures"><i class="fa fa-check"></i><b>6.1.1</b> <strong>Basic measures</strong><span></span></a></li>
<li class="chapter" data-level="6.1.2" data-path="basic-quantitative-geography.html"><a href="basic-quantitative-geography.html#quadrat-analysis"><i class="fa fa-check"></i><b>6.1.2</b> <strong>Quadrat Analysis</strong><span></span></a></li>
<li class="chapter" data-level="6.1.3" data-path="basic-quantitative-geography.html"><a href="basic-quantitative-geography.html#nearest-neighbour-analysis"><i class="fa fa-check"></i><b>6.1.3</b> <strong>Nearest Neighbour Analysis</strong><span></span></a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="basic-quantitative-geography.html"><a href="basic-quantitative-geography.html#spatial-autocorrelation-analysis"><i class="fa fa-check"></i><b>6.2</b> Spatial Autocorrelation Analysis<span></span></a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://bookdown.org" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Spatial Analysis with R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="basic-quantitative-geography" class="section level1 hasAnchor" number="6">
<h1><span class="header-section-number">Chapter 6</span> <strong>Basic Quantitative Geography </strong><a href="basic-quantitative-geography.html#basic-quantitative-geography" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>From chapter 3 to 5, we have learned how to make maps and do spatial operations, they are all fundamental and vital contents regarding spatial analysis. The operations we have learned could help us identify what the space “looks like”; however, up to now, we have no idea about “what space tells.” Hence, this chapter would introduce the basic theory and application of quantitative geography. We would learn the point patterns and spatial auto correlation, which are relatively simple in this field, and can also apply to the analysis on transportation issue. Note that there are much more to explore other than these two elements, if interested, please refer to the textbook <a href="https://vdoc.pub/documents/spatial-data-analysis-an-introduction-for-gis-users-7kgftthl78g0">Spatial Data Analysis - An Introduction For GIS Users</a>.</p>
<p>In this chapter, we require a preliminary knowledge on statistics, especially the concept of hypothetical test.</p>
<div id="point-patterns-analysis" class="section level2 hasAnchor" number="6.1">
<h2><span class="header-section-number">6.1</span> Point Patterns Analysis<a href="basic-quantitative-geography.html#point-patterns-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="basic-measures" class="section level3 hasAnchor" number="6.1.1">
<h3><span class="header-section-number">6.1.1</span> <strong>Basic measures</strong><a href="basic-quantitative-geography.html#basic-measures" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Two commonly used summary measures of point pattern analysis are the mean center and the standard distance. The mean center of a point pattern implies the central tendency of the whole points. It is simply the mean of the x and y coordinates:</p>
<p><span class="math display">\[\bar{\bf{x}}=(\frac{\sum_{i=1}^n \ {x_i}}{n}, \quad \frac{\sum_{i=1}^n \ {y_i}}{n})\]</span>
In the equation above, the bold letter <span class="math inline">\(\bar{\bf{x}}\)</span> represents a vector of X and Y coordinates, and the number of points is <span class="math inline">\(n\)</span>. Besides mean, the other basic statistic is “standard deviation,” that is, the standard distance in the spatial analysis. This standard distance can be interpreted as the dispersion around the mean center:</p>
<p><span class="math display">\[{d_s}=\sqrt{\frac{\sum_{i=1}^n \ {{(x_i-\mu_x)}^2+{(y_i-\mu_y)}^2}}{n}}\]</span></p>
<p><img src="graph/center_analysis_figure.png" width="20%" style="display: block; margin: auto;" /></p>
<p>As for the center analysis, we may come up with the function <a href="spatial-operations.html#centroid"><code>st_centroid</code></a>. However, the function can only use on the center of polygon, it can not retrieve the center of multiple points. An easiest way is to do the summary of X and Y coordinates of the whole points. Take Taipei YouBike for instance. <font color="red"><em><em>Data needed has been downloaded previously. You placed the file in the same directory as the R script file.</em></em> Click <a href="https://github.com/ChiaJung-Yeh/Spatial-Analysis/raw/master/data.zip"><strong>here</strong></a> to re-download the file if it is lost.</font> First, we need to convert X and Y coordinates by using <code>st_coordinates()</code>, and then, just calculate the mean and standard deviation on the data converted.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="basic-quantitative-geography.html#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># import the shapefile</span></span>
<span id="cb1-2"><a href="basic-quantitative-geography.html#cb1-2" aria-hidden="true" tabindex="-1"></a>taipei_youbike<span class="ot">=</span><span class="fu">read_sf</span>(<span class="st">&quot;./data/taipei_youbike/taipei_youbike.shp&quot;</span>)</span>
<span id="cb1-3"><a href="basic-quantitative-geography.html#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="basic-quantitative-geography.html#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># retrieve the coordinated of the points</span></span>
<span id="cb1-5"><a href="basic-quantitative-geography.html#cb1-5" aria-hidden="true" tabindex="-1"></a>taipei_youbike_coor<span class="ot">=</span><span class="fu">st_coordinates</span>(taipei_youbike)</span>
<span id="cb1-6"><a href="basic-quantitative-geography.html#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="basic-quantitative-geography.html#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate mean and standard deviation</span></span>
<span id="cb1-8"><a href="basic-quantitative-geography.html#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">apply</span>(taipei_youbike_coor, <span class="dv">2</span>, <span class="at">FUN=</span>mean)</span></code></pre></div>
<pre><code>##         X         Y 
##  304679.5 2771747.9</code></pre>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="basic-quantitative-geography.html#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">apply</span>(taipei_youbike_coor, <span class="dv">2</span>, <span class="at">FUN=</span>var)<span class="sc">^</span><span class="fl">0.5</span></span></code></pre></div>
<pre><code>##        X        Y 
## 3143.041 3905.884</code></pre>
<p>From the results above, we can know that the mean of X is 304679.5, while the mean of Y is 2771747.9. Also the standard deviation of X and Y are 3143.041 and 3905.884 respectively. Thus, the standard distance would be <span class="math inline">\(\sqrt{(3143.041^2+3905.884^2)}=5013.45\)</span> meters. Figure below shows the center and standard distance of Taipei YouBike.</p>
<p><img src="series_files/figure-html/center_map-1.png" width="750" style="display: block; margin: auto;" /></p>
<p>There is another package called <code>aspace</code> that can calculate the center and standard distance directly. But very unfortunately, this package has been removed from CRAN recently. Thus, please download the zip file <a href="https://github.com/ChiaJung-Yeh/Spatial-Analysis/raw/master/data.zip"><strong>here</strong></a>, and place it into the same directory as your R script file. The installation code from the local is as follows.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="basic-quantitative-geography.html#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;devtools&quot;</span>)</span>
<span id="cb5-2"><a href="basic-quantitative-geography.html#cb5-2" aria-hidden="true" tabindex="-1"></a>devtools<span class="sc">::</span><span class="fu">install_local</span>(<span class="st">&quot;./aspace-master.zip&quot;</span>)</span>
<span id="cb5-3"><a href="basic-quantitative-geography.html#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(aspace)</span></code></pre></div>
<p>Now, let’s again use YouBike data to retrieve its center and standard distance by function <code>mean_centre()</code> and <code>calc_sdd</code> provided by package <code>aspace</code>.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="basic-quantitative-geography.html#cb6-1" aria-hidden="true" tabindex="-1"></a>youbike_center<span class="ot">=</span><span class="fu">mean_centre</span>(<span class="at">points=</span>taipei_youbike_coor)</span></code></pre></div>
<pre><code>##   id CENTRE.x CENTRE.y
## 1  1 304679.5  2771748</code></pre>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="basic-quantitative-geography.html#cb8-1" aria-hidden="true" tabindex="-1"></a>youbike_sdd<span class="ot">=</span><span class="fu">calc_sdd</span>(<span class="at">points=</span>taipei_youbike_coor)</span></code></pre></div>
<pre><code>## $id
## [1] 1
## 
## $calccentre
## [1] TRUE
## 
## $weighted
## [1] FALSE
## 
## $CENTRE.x
## [1] 304679.5
## 
## $CENTRE.y
## [1] 2771748
## 
## $SDD.radius
## [1] 5016.196
## 
## $SDD.area
## [1] 79049460</code></pre>
<p>We can find that the result from two methods are approximately the same. Note that <code>$SDD.radius</code> represents the standard distance, and it causes only 3 meters difference from what we calculate above. In addition, there is a function called <code>CF()</code> that can identify the central feature within a set of point locations. That is, the center of the points must be one of the points.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="basic-quantitative-geography.html#cb10-1" aria-hidden="true" tabindex="-1"></a>youbike_center_CF<span class="ot">=</span><span class="fu">CF</span>(<span class="at">points=</span><span class="fu">data.frame</span>(taipei_youbike_coor))</span></code></pre></div>
<pre><code>##   id     CF.x    CF.y
## 1  1 304864.8 2770973</code></pre>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="basic-quantitative-geography.html#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># use left_join() to find out what the station is</span></span>
<span id="cb12-2"><a href="basic-quantitative-geography.html#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">left_join</span>(youbike_center_CF, <span class="fu">cbind</span>(taipei_youbike, <span class="fu">st_coordinates</span>(taipei_youbike)), <span class="at">by=</span><span class="fu">c</span>(<span class="st">&quot;CF.x&quot;</span><span class="ot">=</span><span class="st">&quot;X&quot;</span>, <span class="st">&quot;CF.y&quot;</span><span class="ot">=</span><span class="st">&quot;Y&quot;</span>))<span class="sc">%&gt;%</span></span>
<span id="cb12-3"><a href="basic-quantitative-geography.html#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(StatnNm, CF.x, CF.y)</span></code></pre></div>
<pre><code>##                   StatnNm     CF.x    CF.y
## 1 YouBike1.0_復興市民路口 304864.8 2770973</code></pre>
<p><img src="series_files/figure-html/center_youbike_map-1.png" width="750" style="display: block; margin: auto;" /></p>
<p>Besides the general calculation of center and standard distance, package <code>aspace</code> can also consider the weights. The general center can only represent the geographical position, but cannot reflect the one affected by the social and economic factors. Now let’s move on to the shapefile of Taipei village in the downloaded data, which contains the attribute of population for each village. And our purpose is to find out the “geographical centroid” and the “center of the population density” of each district in Taipei City. Obtaining these two values, we can compare the difference of two kind of points, and explain the implications.</p>
<p>For the centroid of town, simply use function <a href="spatial-operations.html#centroid"><code>st_centroid()</code></a> to retrieve the center of each district. As for the calculation of weighted center, it is suggested to use <code>for</code> loop. First of all, we need to calculate the population density of each village, which equals to population divided by the area. Then, finding the centroid of each village by function <code>st_centroid()</code> to be the representative point of the village. Next, use function <code>mean_centre()</code> and set the parameters <code>weighted=T</code> and <code>weights=...</code>, to calculate the center of all the points revised by the weight of population density. And, also, apply function <code>calc_sdd()</code> to calculate the standard distance under the influence of weight. The code and result are shown below.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="basic-quantitative-geography.html#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># import shapefile</span></span>
<span id="cb14-2"><a href="basic-quantitative-geography.html#cb14-2" aria-hidden="true" tabindex="-1"></a>village<span class="ot">=</span><span class="fu">read_sf</span>(<span class="st">&quot;./data/taipei_map/taipei_village_map.shp&quot;</span>)</span>
<span id="cb14-3"><a href="basic-quantitative-geography.html#cb14-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-4"><a href="basic-quantitative-geography.html#cb14-4" aria-hidden="true" tabindex="-1"></a>weight_analysis<span class="ot">=</span><span class="fu">data.frame</span>()</span>
<span id="cb14-5"><a href="basic-quantitative-geography.html#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="fu">unique</span>(village<span class="sc">$</span>TOWNNAME)){</span>
<span id="cb14-6"><a href="basic-quantitative-geography.html#cb14-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># filter the town</span></span>
<span id="cb14-7"><a href="basic-quantitative-geography.html#cb14-7" aria-hidden="true" tabindex="-1"></a>  village_dis<span class="ot">=</span><span class="fu">filter</span>(village, TOWNNAME<span class="sc">==</span>i)</span>
<span id="cb14-8"><a href="basic-quantitative-geography.html#cb14-8" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb14-9"><a href="basic-quantitative-geography.html#cb14-9" aria-hidden="true" tabindex="-1"></a>  <span class="co"># find the centroid of town</span></span>
<span id="cb14-10"><a href="basic-quantitative-geography.html#cb14-10" aria-hidden="true" tabindex="-1"></a>  town_center<span class="ot">=</span><span class="fu">st_centroid</span>(<span class="fu">filter</span>(town, TOWNNAME<span class="sc">==</span>i))</span>
<span id="cb14-11"><a href="basic-quantitative-geography.html#cb14-11" aria-hidden="true" tabindex="-1"></a>  town_center<span class="ot">=</span><span class="fu">st_coordinates</span>(town_center)</span>
<span id="cb14-12"><a href="basic-quantitative-geography.html#cb14-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-13"><a href="basic-quantitative-geography.html#cb14-13" aria-hidden="true" tabindex="-1"></a>  <span class="co"># find the centroid of each village (representative points)</span></span>
<span id="cb14-14"><a href="basic-quantitative-geography.html#cb14-14" aria-hidden="true" tabindex="-1"></a>  village_center<span class="ot">=</span><span class="fu">st_centroid</span>(village_dis)</span>
<span id="cb14-15"><a href="basic-quantitative-geography.html#cb14-15" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb14-16"><a href="basic-quantitative-geography.html#cb14-16" aria-hidden="true" tabindex="-1"></a>  <span class="co"># retrieve the coordinate of each point</span></span>
<span id="cb14-17"><a href="basic-quantitative-geography.html#cb14-17" aria-hidden="true" tabindex="-1"></a>  village_center_coor<span class="ot">=</span><span class="fu">st_coordinates</span>(village_center)</span>
<span id="cb14-18"><a href="basic-quantitative-geography.html#cb14-18" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb14-19"><a href="basic-quantitative-geography.html#cb14-19" aria-hidden="true" tabindex="-1"></a>  <span class="co"># set the weights as population density</span></span>
<span id="cb14-20"><a href="basic-quantitative-geography.html#cb14-20" aria-hidden="true" tabindex="-1"></a>  <span class="co"># population density = population / area</span></span>
<span id="cb14-21"><a href="basic-quantitative-geography.html#cb14-21" aria-hidden="true" tabindex="-1"></a>  <span class="co"># st_area retrieves &quot;unit&quot; type data, and the unit is m^2, thus use as.numeric to convert it, and divide by 1,000,000</span></span>
<span id="cb14-22"><a href="basic-quantitative-geography.html#cb14-22" aria-hidden="true" tabindex="-1"></a>  village_center_pd<span class="ot">=</span><span class="fu">mean_centre</span>(<span class="at">points=</span>village_center_coor, <span class="at">weighted=</span>T, <span class="at">weights=</span>(village_dis<span class="sc">$</span>PP<span class="sc">/</span>(<span class="fu">as.numeric</span>(<span class="fu">st_area</span>(village_dis))<span class="sc">/</span><span class="dv">1000000</span>)))</span>
<span id="cb14-23"><a href="basic-quantitative-geography.html#cb14-23" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb14-24"><a href="basic-quantitative-geography.html#cb14-24" aria-hidden="true" tabindex="-1"></a>  vil_sdd_pd<span class="ot">=</span><span class="fu">calc_sdd</span>(<span class="at">points=</span>village_center_coor, <span class="at">weighted=</span>T, <span class="at">weights=</span>(village_dis<span class="sc">$</span>PP<span class="sc">/</span>(<span class="fu">as.numeric</span>(<span class="fu">st_area</span>(village_dis))<span class="sc">/</span><span class="dv">1000000</span>)))</span>
<span id="cb14-25"><a href="basic-quantitative-geography.html#cb14-25" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb14-26"><a href="basic-quantitative-geography.html#cb14-26" aria-hidden="true" tabindex="-1"></a>  <span class="co"># store the result in the table</span></span>
<span id="cb14-27"><a href="basic-quantitative-geography.html#cb14-27" aria-hidden="true" tabindex="-1"></a>  weight_analysis<span class="ot">=</span><span class="fu">rbind</span>(weight_analysis, <span class="fu">data.frame</span>(<span class="at">TOWN=</span>i, town_center, village_center_pd[<span class="dv">2</span><span class="sc">:</span><span class="dv">3</span>], vil_sdd_pd<span class="sc">$</span>SDD.radius))</span>
<span id="cb14-28"><a href="basic-quantitative-geography.html#cb14-28" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb14-29"><a href="basic-quantitative-geography.html#cb14-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-30"><a href="basic-quantitative-geography.html#cb14-30" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(weight_analysis)</span></code></pre></div>
<pre><code>##      TOWN        X       Y CENTRE.x CENTRE.y vil_sdd_pd.SDD.radius
## 1  文山區 307943.5 2764644 305750.9  2765138             1387.2986
## 11 中正區 302460.2 2769473 302261.5  2769187             1093.2534
## 12 信義區 307688.8 2769306 307545.2  2770010             1224.0450
## 13 大安區 304841.9 2768863 304819.4  2769310             1238.6796
## 14 萬華區 300190.7 2769123 300484.0  2769100              921.0697
## 15 南港區 311532.8 2769909 309988.0  2771236             1316.9046</code></pre>
<p><img src="series_files/figure-html/center_village_map-1.png" width="750" style="display: block; margin: auto;" /></p>
<p>In the figure shown above, the blue dots represent the geographical centroid, which is the center of the polygons, while the red dots represent the centers weighted by the population density of each village in. Also, the red buffer means the weighted standard distance of each district. Take a closer look on the map. We can find that the district adjacent to the mountanious area, for instance 北投區, 士林區, 文山區, 南港區 have a larger difference between the geographical centroid and the population weighted center. Obviously, it is because people tend to live in plains with abundant living requirements. For the districts near CBD, such as 大同區, the differences between two points are slight.</p>
<p>This can further prove that using “geographical centroid” may not be meaningful, for it does not correspond to the real life. The weighted center can illustrate the population distribution, and even signify the land use of each district in Taipei City. To sum up, learning how to derive the weighted center may be an importaant issue in spatial analysis.</p>
</div>
<div id="quadrat-analysis" class="section level3 hasAnchor" number="6.1.2">
<h3><span class="header-section-number">6.1.2</span> <strong>Quadrat Analysis</strong><a href="basic-quantitative-geography.html#quadrat-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In the previous section, we have learned how to derive the centroid and the standard distance. For these two values, we can roughly realize the central tendency of the points distribution; however, we have no clear clue to tell whether the points distribution is dipersed, dense or random. Now, we would further discuss the density of the points by using a statistical method called <strong>Quadrat Analysis</strong>.</p>
<p>Quadrat analysis is a common method of exploring spatial pattern in the number of events. Specifically, in this analysis, we should first divide the study area into several grids. Then, count the number of points fall within each grid square. After counting the points, we should find a statistical measure to assess the distribution of point counts in grids, and determine whether the distribution is dipersed (uniform distribution), dense (cluster), or random (Poisson distribution). The steps are explained in detail with an simple example.</p>
<p>Figure below shows two cases of the point distribution. The number of points are the same (30) for two cases, but apparently the points pattern are totally different. We can easily observe that the distribution of Case A is dense, and the cluster is obvious, while the distribution of Case B is dipersed, and is approximately uniform distributed.</p>
<p><img src="graph/quard_1.png" width="90%" style="display: block; margin: auto;" /></p>
<p><span style="text-decoration:underline"><strong>STEP 1: Make Grids</strong></span><br />
To do the Quadrat analysis, the initial step is to crop the study area into several grids, and count the number of points in each grid. Take Case A and B for instance. We crop the study area into 7*6=42 grids. For case A, the maximum number of points is 5, while only 2 for Case B.</p>
<p><img src="graph/quard_2.png" width="90%" style="display: block; margin: auto;" /></p>
<p><span style="text-decoration:underline"><strong>STEP 2: Derive Mean &amp; Variance</strong></span><br />
After counting the points in each grid in STEP 1, we need to further calculate the mean and variance of number of counts for all the grids. For Case A, the counts of mean is:</p>
<p><span class="math display">\[\frac{{(0+0+0+1+0+0+0)+(0+0+0+1+0+0+0)+(0+1+4+3+3+0+0)}+...}{6*7}=0.714\]</span></p>
<p>, and the variance is:</p>
<p><span class="math display">\[\frac{{(0-0.714)^2+(0-0.714)^2+(0-0.714)^2+(1-0.714)^2}+...}{6*7-1}=1.770\]</span><br />
Also, the mean and variance of Case B is 0.714 and 0.355 respectively.</p>
<p><span style="text-decoration:underline"><strong>STEP 3: Caluculate VMR</strong></span></p>
<p>Variance/mean ratio (VMR) is an index of dispersion, which is a common measure of assessing the degree of clustering or regularity in a point pattern.</p>
<p><span class="math display">\[VMR=\frac{\sigma^2}{\mu}\]</span></p>
<p>What does it mean if the variance is equal to mean (<span class="math inline">\(VMR=1\)</span>)? Remember the Poisson distribution? It is a discrete distribution that measures the probability of a given number of events happening in a specified time period (or the grid in spatial analysis). Mean and variance must be the same for this distribution!! Proof is attached <a href="https://proofwiki.org/wiki/Variance_of_Poisson_Distribution">here</a>. With this feature, we can say that the number of points are random underlying the Poisson distribution.</p>
<p>The minimum value of VMR is 0, it occurs only if the variance is equal to 0. That is, all of the number of points in each grid is the same, and we can identify this point pattern as perfectly uniform distribution (extremely dipersed). On the contrary, if VMR is larger than 1, it implies that there is too much variation among counts, and we can say that the point pattern is clustering. Figure below summarizes the concept of VMR.</p>
<p><img src="graph/quard_type.png" width="80%" style="display: block; margin: auto;" /></p>
<p>Thus, VMR of Case A is <span class="math inline">\(1.770/0.714=2.479\)</span>, while VMR of case B is <span class="math inline">\(0.355/0.714=0.497\)</span>. Based on the summary in the figure above, we can find that Case A is clustering, and Case B is dipersed.</p>
<p><span style="text-decoration:underline"><strong>STEP 4: Test Statistic</strong></span><br />
However, here comes a question. How do we distinguish between 1.001 and 1, or 0.999 and 1? Do the two values represent random or not? To solve the problem, we should conduct the hypothetical test to examine whether the test statistic result is significant. The null hypothesis is that the points are randomly distributed (<span class="math inline">\(VMR=1\)</span>), namely, Poisson distribution, and it is chi-squared with <span class="math inline">\(N-1\)</span> degrees of freedom. The test statistic of VMR is:</p>
<p><span class="math display">\[\chi^2=(N-1)*VMR\]</span>
, where <span class="math inline">\(N\)</span> is the number of grid cells. After calculating <span class="math inline">\(\chi^2\)</span>, we can check for the chi-square table to examine whether to reject the null hypothesis. And note that VMR statistic test is a two-tail chi-squared test because there are two directions of deviations apart from the random distribution, that is uniform distribution, whose <span class="math inline">\(\chi^2\)</span> would be low, and the clustering, whose <span class="math inline">\(\chi^2\)</span> would be high. Thus, the acceptance of null hypothesis of an adequate fit if:</p>
<p><span class="math display">\[\chi^2_.975\leq\chi^2_{Observed}\leq\chi^2_.025\]</span></p>
<p>For Case A, the Chi-square is <span class="math inline">\((42-1)*2.479=101.639\)</span>. The degree of freedom is <span class="math inline">\(42-1=41\)</span>. Look up chi-square table, the critical value is 45.72 under p value is 0.025. (Or, please use <code>qchisq(0.025, 41, lower.tail=F)</code> in R to find out). Apparently, <span class="math inline">\(74.37&gt;60.56\)</span>, Case A is significant clustering. For Case B, the Chi-square is <span class="math inline">\((42-1)*0.497=20.38\)</span>. The degree of freedom is also <span class="math inline">\(42-1=41\)</span>. Look up chi-square table, the critical value is 25.21 under p value is 0.975. (<code>qchisq(0.975, 41, lower.tail=F)</code>). And because <span class="math inline">\(20.38&lt;25.21\)</span>, Case B is significant dispersed.</p>
<p>Now, let’s use YouBike data to perform quadrat analysis. <font color="red"><em><em>Data needed has been downloaded previously. You placed the file in the same directory as the R script file.</em></em> Click <a href="https://github.com/ChiaJung-Yeh/Spatial-Analysis/raw/master/data.zip"><strong>here</strong></a> to re-download the file if it is lost.</font></p>
</div>
<div id="nearest-neighbour-analysis" class="section level3 hasAnchor" number="6.1.3">
<h3><span class="header-section-number">6.1.3</span> <strong>Nearest Neighbour Analysis</strong><a href="basic-quantitative-geography.html#nearest-neighbour-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h3>
</div>
</div>
<div id="spatial-autocorrelation-analysis" class="section level2 hasAnchor" number="6.2">
<h2><span class="header-section-number">6.2</span> Spatial Autocorrelation Analysis<a href="basic-quantitative-geography.html#spatial-autocorrelation-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h2>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="spatial-operations.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "serif",
"size": 2
},
"edit": {
"link": "https://github.com/ChiaJung-Yeh/Spatial-Analysis/blob/master/05-Basic-Quantitative-Geography.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["series.pdf"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
