<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 5 Spatial Operations | Spatial Analysis with R</title>
  <meta name="description" content="A bookdown book on how to conduct spatial analysis on R." />
  <meta name="generator" content="bookdown 0.22 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 5 Spatial Operations | Spatial Analysis with R" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="A bookdown book on how to conduct spatial analysis on R." />
  <meta name="github-repo" content="openscapes/series" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 5 Spatial Operations | Spatial Analysis with R" />
  
  <meta name="twitter:description" content="A bookdown book on how to conduct spatial analysis on R." />
  

<meta name="author" content="Chia Jung, Yeh" />


<meta name="date" content="2021-08-20" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="geographic-data.html"/>

<script src="libs/header-attrs-2.8/header-attrs.js"></script>
<script src="libs/jquery-3.5.1/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<script src="libs/htmlwidgets-1.5.3/htmlwidgets.js"></script>
<link href="libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet" />
<script src="libs/datatables-binding-0.18/datatables.js"></script>
<link href="libs/dt-core-1.10.20/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="libs/dt-core-1.10.20/css/jquery.dataTables.extra.css" rel="stylesheet" />
<script src="libs/dt-core-1.10.20/js/jquery.dataTables.min.js"></script>
<link href="libs/crosstalk-1.1.1/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.1.1/js/crosstalk.min.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="lib/css/bootstrap.min.css" type="text/css" />
<link rel="stylesheet" href="lib/css/style.css" type="text/css" />
<link rel="stylesheet" href="lib/css/lesson.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Spatial Analysis with R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a></li>
<li class="chapter" data-level="2" data-path="basic-knowledge-on-gis.html"><a href="basic-knowledge-on-gis.html"><i class="fa fa-check"></i><b>2</b> <strong>Basic Knowledge on GIS</strong></a>
<ul>
<li class="chapter" data-level="2.1" data-path="basic-knowledge-on-gis.html"><a href="basic-knowledge-on-gis.html#geographic-information-systems"><i class="fa fa-check"></i><b>2.1</b> Geographic Information Systems</a></li>
<li class="chapter" data-level="2.2" data-path="basic-knowledge-on-gis.html"><a href="basic-knowledge-on-gis.html#well-known-text-wkt"><i class="fa fa-check"></i><b>2.2</b> Well-Known Text (WKT)</a></li>
<li class="chapter" data-level="2.3" data-path="basic-knowledge-on-gis.html"><a href="basic-knowledge-on-gis.html#shapefile"><i class="fa fa-check"></i><b>2.3</b> Shapefile</a></li>
<li class="chapter" data-level="2.4" data-path="basic-knowledge-on-gis.html"><a href="basic-knowledge-on-gis.html#coordinate-reference-system-crs"><i class="fa fa-check"></i><b>2.4</b> Coordinate Reference System (CRS)</a></li>
<li class="chapter" data-level="2.5" data-path="basic-knowledge-on-gis.html"><a href="basic-knowledge-on-gis.html#why-use-r"><i class="fa fa-check"></i><b>2.5</b> Why Use R?</a></li>
<li class="chapter" data-level="2.6" data-path="basic-knowledge-on-gis.html"><a href="basic-knowledge-on-gis.html#required-packages"><i class="fa fa-check"></i><b>2.6</b> Required Packages</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="data-visualization-with-maps.html"><a href="data-visualization-with-maps.html"><i class="fa fa-check"></i><b>3</b> <strong>Data Visualization with Maps</strong></a>
<ul>
<li class="chapter" data-level="3.1" data-path="data-visualization-with-maps.html"><a href="data-visualization-with-maps.html#making-maps"><i class="fa fa-check"></i><b>3.1</b> Making Maps</a></li>
<li class="chapter" data-level="3.2" data-path="data-visualization-with-maps.html"><a href="data-visualization-with-maps.html#attributes-of-shapefile"><i class="fa fa-check"></i><b>3.2</b> Attributes of Shapefile</a></li>
<li class="chapter" data-level="3.3" data-path="data-visualization-with-maps.html"><a href="data-visualization-with-maps.html#labels-on-map"><i class="fa fa-check"></i><b>3.3</b> Labels on Map</a></li>
<li class="chapter" data-level="3.4" data-path="data-visualization-with-maps.html"><a href="data-visualization-with-maps.html#graduated-symbol-map"><i class="fa fa-check"></i><b>3.4</b> Graduated Symbol Map</a></li>
<li class="chapter" data-level="3.5" data-path="data-visualization-with-maps.html"><a href="data-visualization-with-maps.html#categorized-symbol-map"><i class="fa fa-check"></i><b>3.5</b> Categorized Symbol Map</a></li>
<li class="chapter" data-level="3.6" data-path="data-visualization-with-maps.html"><a href="data-visualization-with-maps.html#rule-based-symbol-map"><i class="fa fa-check"></i><b>3.6</b> Rule-based Symbol Map</a></li>
<li class="chapter" data-level="3.7" data-path="data-visualization-with-maps.html"><a href="data-visualization-with-maps.html#basic-operationselements-of-map"><i class="fa fa-check"></i><b>3.7</b> Basic Operations/Elements of Map</a>
<ul>
<li class="chapter" data-level="3.7.1" data-path="data-visualization-with-maps.html"><a href="data-visualization-with-maps.html#map-overlay"><i class="fa fa-check"></i><b>3.7.1</b> <strong>Map Overlay</strong></a></li>
<li class="chapter" data-level="3.7.2" data-path="data-visualization-with-maps.html"><a href="data-visualization-with-maps.html#north-arrow-and-scale"><i class="fa fa-check"></i><b>3.7.2</b> <strong>North Arrow and Scale</strong></a></li>
<li class="chapter" data-level="3.7.3" data-path="data-visualization-with-maps.html"><a href="data-visualization-with-maps.html#linetypeshape"><i class="fa fa-check"></i><b>3.7.3</b> <strong>Linetype/Shape</strong></a></li>
<li class="chapter" data-level="3.7.4" data-path="data-visualization-with-maps.html"><a href="data-visualization-with-maps.html#theme"><i class="fa fa-check"></i><b>3.7.4</b> <strong>Theme</strong></a></li>
</ul></li>
<li class="chapter" data-level="3.8" data-path="data-visualization-with-maps.html"><a href="data-visualization-with-maps.html#other-mapping-tools"><i class="fa fa-check"></i><b>3.8</b> Other Mapping Tools</a>
<ul>
<li class="chapter" data-level="3.8.1" data-path="data-visualization-with-maps.html"><a href="data-visualization-with-maps.html#tmap"><i class="fa fa-check"></i><b>3.8.1</b> <strong>tmap</strong></a></li>
<li class="chapter" data-level="3.8.2" data-path="data-visualization-with-maps.html"><a href="data-visualization-with-maps.html#leaflet"><i class="fa fa-check"></i><b>3.8.2</b> <strong>leaflet</strong></a></li>
</ul></li>
<li class="chapter" data-level="3.9" data-path="data-visualization-with-maps.html"><a href="data-visualization-with-maps.html#practice"><i class="fa fa-check"></i><b>3.9</b> <span style="border-bottom: 3px double black"><em><em>PRACTICE</em></em></span></a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="geographic-data.html"><a href="geographic-data.html"><i class="fa fa-check"></i><b>4</b> <strong>Geographic Data</strong></a>
<ul>
<li class="chapter" data-level="4.1" data-path="geographic-data.html"><a href="geographic-data.html#simple-feature-geometries-sfg"><i class="fa fa-check"></i><b>4.1</b> Simple Feature Geometries (sfg)</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="geographic-data.html"><a href="geographic-data.html#point"><i class="fa fa-check"></i><b>4.1.1</b> <strong>Point</strong></a></li>
<li class="chapter" data-level="4.1.2" data-path="geographic-data.html"><a href="geographic-data.html#linestring"><i class="fa fa-check"></i><b>4.1.2</b> <strong>Linestring</strong></a></li>
<li class="chapter" data-level="4.1.3" data-path="geographic-data.html"><a href="geographic-data.html#polygon"><i class="fa fa-check"></i><b>4.1.3</b> <strong>Polygon</strong></a></li>
<li class="chapter" data-level="4.1.4" data-path="geographic-data.html"><a href="geographic-data.html#multipoint"><i class="fa fa-check"></i><b>4.1.4</b> <strong>Multipoint</strong></a></li>
<li class="chapter" data-level="4.1.5" data-path="geographic-data.html"><a href="geographic-data.html#multilinestring"><i class="fa fa-check"></i><b>4.1.5</b> <strong>Multilinestring</strong></a></li>
<li class="chapter" data-level="4.1.6" data-path="geographic-data.html"><a href="geographic-data.html#multipolygon"><i class="fa fa-check"></i><b>4.1.6</b> <strong>Multipolygon</strong></a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="geographic-data.html"><a href="geographic-data.html#simple-feature-columns-sfc"><i class="fa fa-check"></i><b>4.2</b> Simple Feature Columns (sfc)</a></li>
<li class="chapter" data-level="4.3" data-path="geographic-data.html"><a href="geographic-data.html#simple-feature-sf"><i class="fa fa-check"></i><b>4.3</b> Simple Feature (sf)</a></li>
<li class="chapter" data-level="4.4" data-path="geographic-data.html"><a href="geographic-data.html#convert-text-file-to-shapefile"><i class="fa fa-check"></i><b>4.4</b> Convert Text File to Shapefile</a></li>
<li class="chapter" data-level="4.5" data-path="geographic-data.html"><a href="geographic-data.html#reproject-geographic-data"><i class="fa fa-check"></i><b>4.5</b> Reproject Geographic Data</a></li>
<li class="chapter" data-level="4.6" data-path="geographic-data.html"><a href="geographic-data.html#geographic-data-export"><i class="fa fa-check"></i><b>4.6</b> Geographic Data Export</a></li>
<li class="chapter" data-level="4.7" data-path="geographic-data.html"><a href="geographic-data.html#geographic-data-format"><i class="fa fa-check"></i><b>4.7</b> Geographic Data Format</a></li>
<li class="chapter" data-level="4.8" data-path="geographic-data.html"><a href="geographic-data.html#join-attribute-and-spatial-data"><i class="fa fa-check"></i><b>4.8</b> Join Attribute and Spatial Data</a></li>
<li class="chapter" data-level="4.9" data-path="geographic-data.html"><a href="geographic-data.html#practice-1"><i class="fa fa-check"></i><b>4.9</b> <span style="border-bottom: 3px double black"><em><em>PRACTICE</em></em></span></a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="spatial-operations.html"><a href="spatial-operations.html"><i class="fa fa-check"></i><b>5</b> <strong>Spatial Operations</strong></a>
<ul>
<li class="chapter" data-level="5.1" data-path="spatial-operations.html"><a href="spatial-operations.html#spatial-join"><i class="fa fa-check"></i><b>5.1</b> Spatial Join</a></li>
<li class="chapter" data-level="5.2" data-path="spatial-operations.html"><a href="spatial-operations.html#attribute-aggregation"><i class="fa fa-check"></i><b>5.2</b> Attribute Aggregation</a></li>
<li class="chapter" data-level="5.3" data-path="spatial-operations.html"><a href="spatial-operations.html#spatial-aggregation"><i class="fa fa-check"></i><b>5.3</b> Spatial Aggregation</a></li>
<li class="chapter" data-level="5.4" data-path="spatial-operations.html"><a href="spatial-operations.html#interpolation"><i class="fa fa-check"></i><b>5.4</b> Interpolation</a></li>
<li class="chapter" data-level="5.5" data-path="spatial-operations.html"><a href="spatial-operations.html#unions"><i class="fa fa-check"></i><b>5.5</b> Unions</a></li>
<li class="chapter" data-level="5.6" data-path="spatial-operations.html"><a href="spatial-operations.html#centroid"><i class="fa fa-check"></i><b>5.6</b> Centroid</a></li>
<li class="chapter" data-level="5.7" data-path="spatial-operations.html"><a href="spatial-operations.html#buffer"><i class="fa fa-check"></i><b>5.7</b> Buffer</a></li>
<li class="chapter" data-level="5.8" data-path="spatial-operations.html"><a href="spatial-operations.html#boundary"><i class="fa fa-check"></i><b>5.8</b> Boundary</a></li>
<li class="chapter" data-level="5.9" data-path="spatial-operations.html"><a href="spatial-operations.html#clipping"><i class="fa fa-check"></i><b>5.9</b> Clipping</a></li>
<li class="chapter" data-level="5.10" data-path="spatial-operations.html"><a href="spatial-operations.html#simplification"><i class="fa fa-check"></i><b>5.10</b> Simplification</a></li>
<li class="chapter" data-level="5.11" data-path="spatial-operations.html"><a href="spatial-operations.html#affine-transformations"><i class="fa fa-check"></i><b>5.11</b> Affine Transformations</a></li>
<li class="chapter" data-level="5.12" data-path="spatial-operations.html"><a href="spatial-operations.html#geometric-measurement"><i class="fa fa-check"></i><b>5.12</b> Geometric Measurement</a></li>
<li class="chapter" data-level="5.13" data-path="spatial-operations.html"><a href="spatial-operations.html#nearest-analysis"><i class="fa fa-check"></i><b>5.13</b> Nearest Analysis</a></li>
<li class="chapter" data-level="5.14" data-path="spatial-operations.html"><a href="spatial-operations.html#convex-hull"><i class="fa fa-check"></i><b>5.14</b> Convex Hull</a></li>
<li class="chapter" data-level="5.15" data-path="spatial-operations.html"><a href="spatial-operations.html#voronoi-polygon"><i class="fa fa-check"></i><b>5.15</b> Voronoi Polygon</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://bookdown.org" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Spatial Analysis with R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="spatial-operations" class="section level1" number="5">
<h1><span class="header-section-number">Chapter 5</span> <strong>Spatial Operations</strong></h1>
<p>We have learned how geographic datasets are structured in R, and how to join the spatial and attribute features. In this chapter, we would further discuss about the skills of spatial operations. Imagine that we want to know the number of schools in each villages, we should intersect the school point layer and village polygon layer, to identify the polygon for each point located on. “Intersection” is a type of spatial operations. Or imagine we want to know whether there are schools within 500 meters of MRT stations. We need to draw buffer of the stations in advance. “Buffer” is also a type of spatial operations. From the examples above, we find that spatial operations are vital in the spatial analysis.</p>
<p>We would introduce some common spatial operation functions in package sf. But please note that we would also use some functions in package <code>dplyr</code>. If you are not acquainted with the package, please read the notebook attached <a href="https://rpubs.com/WeiLunChiang/dplyr">here</a>, which provides you with a quick learn on the major function in <code>dplyr</code> More detailed information of dplyr is supplied in <a href="https://r4ds.had.co.nz/transform.html">Chapter 5 of R for Data Science</a>.</p>
<div id="spatial-join" class="section level2" number="5.1">
<h2><span class="header-section-number">5.1</span> Spatial Join</h2>
<p>As we have learned in the <a href="geographic-data.html#join-attribute-and-spatial-data">previous chapter</a>, joining spatial and attribute data requires a primary key, namely a common column variable. But what if we want to join two spatial data? It applies the similar concept, but relies on the shared areas of geographic space (spatial overlay). We can apply function <code>st_join(x, y, left)</code>. The target object which would be in the left part of the new data frame is placed in the first parameter (x), while the joined object is placed in the second parameter (y). Parameter <code>left=</code> represents whether do the left join or not, which is <code>left=T</code> by default, and return all records of the x object with y fields. If <code>left=F</code>, then do the inner join instead.</p>
<p>Take nz and nz_height in spData for instance. The former data is the map of New Zealand, while the latter is the top 101 highest points in the country. In the example below, we want to know which provinces those points are located in.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="spatial-operations.html#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_join</span>(nz_height, nz[<span class="st">&quot;Name&quot;</span>])</span></code></pre></div>
<pre><code>## Simple feature collection with 101 features and 3 fields
## Geometry type: POINT
## Dimension:     XY
## Bounding box:  xmin: 1204143 ymin: 5048309 xmax: 1822492 ymax: 5650492
## Projected CRS: NZGD2000 / New Zealand Transverse Mercator 2000
## First 10 features:
##    t50_fid elevation       Name                geometry
## 1  2353944      2723  Southland POINT (1204143 5049971)
## 2  2354404      2820      Otago POINT (1234725 5048309)
## 3  2354405      2830      Otago POINT (1235915 5048745)
## 4  2369113      3033 West Coast POINT (1259702 5076570)
## 5  2362630      2749 Canterbury POINT (1378170 5158491)
## 6  2362814      2822 Canterbury POINT (1389460 5168749)
## 7  2362817      2778 Canterbury POINT (1390166 5169466)
## 8  2363991      3004 Canterbury POINT (1372357 5172729)
## 9  2363993      3114 Canterbury POINT (1372062 5173236)
## 10 2363994      2882 Canterbury POINT (1372810 5173419)</code></pre>
<p>Please note that we should remain the class sf in two parameters. Thus, second parameter in function <code>st_join()</code> should not be <code>nz$name</code>, which is a numeric type. Use <code>nz["Name"]</code> instead, to remain the spatial data.</p>
<p>You may be confused about the sequence of data placed in function <code>st_join()</code>. Let’s do a simple comparison. In <code>st_join(nz_height, nz)</code>, nz_height is target data, and hence the new data frame is based on all the highest points, and the geometry remains the form of nz_height (point). In <code>st_join(nz, nz_height)</code>, nz is the target data, and hence the new data frame is based on the province, and the geometry remains the form of nz (polygon). Try the code yourself might get a better knowing.</p>
<p>Note that <code>st_join(..., join=st_intersects)</code> does the intersection operation by default. If we want to do other operations, we need to revise the parameter <code>join=</code> in <code>st_join(..., join=)</code>. Function used in <code>join=</code> is listed in documentation of <a href="https://www.rdocumentation.org/packages/sf/versions/0.9-7/topics/geos_binary_pred"><code>geos_binary_pred</code></a>. The features are simply introduced in the table below (not all the functions are appropriate to be applied in <code>st_join</code>).</p>
<p><span id="geos_binary_pred"></span></p>
<table class="table table-striped table-hover" style="font-size: 14px; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
Function
</th>
<th style="text-align:left;">
Features
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;width: 5em; ">
<strong><code>st_intersects(x,y)</code></strong>
</td>
<td style="text-align:left;width: 29em; ">
identifies if x and y geometry share any space
</td>
</tr>
<tr>
<td style="text-align:left;width: 5em; ">
<strong><code>st_contains(x,y)</code></strong>
</td>
<td style="text-align:left;width: 29em; ">
identifies if x is within y (i.e. point within polygon)
</td>
</tr>
<tr>
<td style="text-align:left;width: 5em; ">
<strong><code>st_disjoint(x,y)</code></strong>
</td>
<td style="text-align:left;width: 29em; ">
identifies when geometries from x do not share space with y
</td>
</tr>
<tr>
<td style="text-align:left;width: 5em; ">
<strong><code>st_crosses(x,y)</code></strong>
</td>
<td style="text-align:left;width: 29em; ">
identifies if any geometry of x have commonalities with y
</td>
</tr>
<tr>
<td style="text-align:left;width: 5em; ">
<strong><code>st_covers(x,y)</code></strong>
</td>
<td style="text-align:left;width: 29em; ">
identifies if any point from x is outside of y (i.e. polygon outside polygon)
</td>
</tr>
<tr>
<td style="text-align:left;width: 5em; ">
<strong><code>st_covered_by(x,y)</code></strong>
</td>
<td style="text-align:left;width: 29em; ">
identifies if x is completely within y (i.e. polygon completely within polygon)
</td>
</tr>
<tr>
<td style="text-align:left;width: 5em; ">
<strong><code>st_within(x,y)</code></strong>
</td>
<td style="text-align:left;width: 29em; ">
identifies if x is in a specified distance to y
</td>
</tr>
<tr>
<td style="text-align:left;width: 5em; ">
<strong><code>st_touches(x,y)</code></strong>
</td>
<td style="text-align:left;width: 29em; ">
identifies if geometries of x and y share a common point but their interiors do not intersect
</td>
</tr>
</tbody>
</table>
</div>
<div id="attribute-aggregation" class="section level2" number="5.2">
<h2><span class="header-section-number">5.2</span> Attribute Aggregation</h2>
<p>Aggregation operations summarize datasets (including attributes and spatial features) by a “grouping variable.” We can use function <code>group_by() %&gt;% summarise()</code> in <code>dplyr</code> to conduct aggregation. Let’s take data “world” for example. We want to group by the data by continent, and summarize the total population of each continent. The code and result are shown below.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="spatial-operations.html#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># map before aggregation</span></span>
<span id="cb3-2"><a href="spatial-operations.html#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(world)<span class="sc">+</span></span>
<span id="cb3-3"><a href="spatial-operations.html#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>()<span class="sc">+</span></span>
<span id="cb3-4"><a href="spatial-operations.html#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">panel.background=</span><span class="fu">element_blank</span>())</span></code></pre></div>
<p><img src="series_files/figure-html/aggregation_1-1.png" width="1200" /></p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="spatial-operations.html#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># aggregation operations</span></span>
<span id="cb4-2"><a href="spatial-operations.html#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="spatial-operations.html#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="co"># group_by(Data, Grouping_variable)%&gt;%</span></span>
<span id="cb4-4"><a href="spatial-operations.html#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="co">#   summarise(New_column=Operation(Operated_variable))</span></span>
<span id="cb4-5"><a href="spatial-operations.html#cb4-5" aria-hidden="true" tabindex="-1"></a>continent_pop<span class="ot">=</span><span class="fu">group_by</span>(world, continent)<span class="sc">%&gt;%</span></span>
<span id="cb4-6"><a href="spatial-operations.html#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">pop=</span><span class="fu">sum</span>(pop, <span class="at">na.rm=</span>T))</span>
<span id="cb4-7"><a href="spatial-operations.html#cb4-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-8"><a href="spatial-operations.html#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="co"># glance at new data</span></span>
<span id="cb4-9"><a href="spatial-operations.html#cb4-9" aria-hidden="true" tabindex="-1"></a>continent_pop</span></code></pre></div>
<pre><code>## Simple feature collection with 8 features and 2 fields
## Geometry type: MULTIPOLYGON
## Dimension:     XY
## Bounding box:  xmin: -180 ymin: -90 xmax: 180 ymax: 83.64513
## Geodetic CRS:  WGS 84
## # A tibble: 8 x 3
##   continent              pop                                                geom
##   &lt;chr&gt;                &lt;dbl&gt;                         &lt;MULTIPOLYGON [arc_degree]&gt;
## 1 Africa              1.15e9 (((-16.71373 13.59496, -17.12611 14.37352, -17.625~
## 2 Antarctica          0      (((-48.66062 -78.04702, -48.1514 -78.04707, -46.66~
## 3 Asia                4.31e9 (((27.19238 40.69057, 26.35801 40.15199, 26.04335 ~
## 4 Europe              6.69e8 (((-177.6636 71.13277, -178.6938 70.89302, -180 70~
## 5 North America       5.65e8 (((-169.5294 62.97693, -170.2906 63.19444, -170.67~
## 6 Oceania             3.78e7 (((-179.7933 -16.02088, -179.9174 -16.50178, -180 ~
## 7 Seven seas (open~   0      (((68.935 -48.625, 69.58 -48.94, 70.525 -49.065, 7~
## 8 South America       4.12e8 (((-71.37525 -17.7738, -71.46204 -17.36349, -73.44~</code></pre>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="spatial-operations.html#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># map after aggregation</span></span>
<span id="cb6-2"><a href="spatial-operations.html#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(continent_pop)<span class="sc">+</span></span>
<span id="cb6-3"><a href="spatial-operations.html#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>()<span class="sc">+</span></span>
<span id="cb6-4"><a href="spatial-operations.html#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">panel.background=</span><span class="fu">element_blank</span>())</span></code></pre></div>
<p><img src="series_files/figure-html/aggregation_1-2.png" width="1200" /></p>
<p>After aggregation, we can find that the population (attribute) has been summed up based on the continent. The geometry is also aggregated by it, which eliminate the border of each country. The geometry of new map represents the border of each continent.</p>
<p>Here let’s do more practice on the function of <code>dplyr</code> Suppose we want to retrieve the data of total population, average life expectancy and the number of countries by subregion. Then, arrange the data by average life expectancy in descending order. The code is shown below.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="spatial-operations.html#cb7-1" aria-hidden="true" tabindex="-1"></a>subregion_info<span class="ot">=</span><span class="fu">group_by</span>(world, subregion)<span class="sc">%&gt;%</span></span>
<span id="cb7-2"><a href="spatial-operations.html#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb7-3"><a href="spatial-operations.html#cb7-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">pop=</span><span class="fu">sum</span>(pop, <span class="at">na.rm=</span>T),              <span class="co"># use function sum() to calculate total population</span></span>
<span id="cb7-4"><a href="spatial-operations.html#cb7-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">lifeExp=</span><span class="fu">mean</span>(lifeExp, <span class="at">na.rm=</span>T),     <span class="co"># use function mean() to calculate average life expectancy</span></span>
<span id="cb7-5"><a href="spatial-operations.html#cb7-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">num_cou=</span><span class="fu">n</span>()                         <span class="co"># use function n() to calculate total number in each group</span></span>
<span id="cb7-6"><a href="spatial-operations.html#cb7-6" aria-hidden="true" tabindex="-1"></a>  )<span class="sc">%&gt;%</span></span>
<span id="cb7-7"><a href="spatial-operations.html#cb7-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(lifeExp))                <span class="co"># use arrange to order data, and desc() means descending order</span></span>
<span id="cb7-8"><a href="spatial-operations.html#cb7-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-9"><a href="spatial-operations.html#cb7-9" aria-hidden="true" tabindex="-1"></a><span class="co"># glance at new data</span></span>
<span id="cb7-10"><a href="spatial-operations.html#cb7-10" aria-hidden="true" tabindex="-1"></a>subregion_info</span></code></pre></div>
<pre><code>## Simple feature collection with 22 features and 4 fields
## Geometry type: GEOMETRY
## Dimension:     XY
## Bounding box:  xmin: -180 ymin: -90 xmax: 180 ymax: 83.64513
## Geodetic CRS:  WGS 84
## # A tibble: 22 x 5
##    subregion          pop lifeExp num_cou                                   geom
##    &lt;chr&gt;            &lt;dbl&gt;   &lt;dbl&gt;   &lt;int&gt;                &lt;GEOMETRY [arc_degree]&gt;
##  1 Australia and~  2.80e7    81.9       2 MULTIPOLYGON (((124.2216 -32.95949, 1~
##  2 Western Europe  1.26e8    81.8       7 MULTIPOLYGON (((-52.93966 2.124858, -~
##  3 Northern Amer~  3.54e8    80.4       3 MULTIPOLYGON (((-169.5294 62.97693, -~
##  4 Northern Euro~  9.66e7    79.5      10 MULTIPOLYGON (((-17.79444 63.67875, -~
##  5 Southern Euro~  1.53e8    78.4      12 MULTIPOLYGON (((-8.898857 36.86881, -~
##  6 Eastern Asia    1.57e9    76.3       6 MULTIPOLYGON (((121.586 39.36085, 121~
##  7 Central Ameri~  1.70e8    74.7       8 POLYGON ((-93.87517 15.94016, -94.691~
##  8 Western Asia    2.52e8    74.5      18 MULTIPOLYGON (((28.80644 41.05496, 27~
##  9 Eastern Europe  2.93e8    74.5      10 MULTIPOLYGON (((-177.5779 71.26948, -~
## 10 Caribbean       4.06e7    73.8       7 MULTIPOLYGON (((-79.28149 22.3992, -7~
## # ... with 12 more rows</code></pre>
<p>Function <code>sum()</code> obtains the total value; <code>mean()</code> obtains the average value; <code>n()</code> obtains the total number in the group. Parameter <code>na.rm=T</code> means that the calculation would skip the NA (not available). If we do not add this parameter, the result would be NA as well. Parameter <code>desc()</code> means arrange the data in descending order, or it would be in ascending order by default. As we can see in the result printed above, the first three highest life expectancy are Australia and New Zealand, Western Europe, and Northern America respectively.</p>
<p>In addition to the application of <code>dplyr</code>, we can use function <code>aggregate()</code> provided by package <code>sf</code> to obtain the same result. The first parameter in the function is the data we want to summarize. Note the data should be remain the sf features. Thus, do not use the form like <code>world$pop</code>, whose type is “numeric.” Instead, we should write in the form as <code>world["pop"]</code>, whose type is “sf” and “dataframe.” Parameter <code>by=</code> should be filled in with the columns we want to group by. Note that the type of data should be a list. Parameter <code>FUN</code> is the spatial operation such as sum or average. Last, if the data contains NA, we should add the parameter <code>na.rm=T</code>, in order to skip NA. Again, take data “world” for example, and group by the data by continent, summarize the total population of each continent. The code and result are as follows.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="spatial-operations.html#cb9-1" aria-hidden="true" tabindex="-1"></a>continent_pop_ag<span class="ot">=</span><span class="fu">aggregate</span>(world[<span class="st">&quot;pop&quot;</span>], <span class="at">by=</span><span class="fu">list</span>(world<span class="sc">$</span>continent), <span class="at">FUN=</span>sum, <span class="at">na.rm=</span>T)</span>
<span id="cb9-2"><a href="spatial-operations.html#cb9-2" aria-hidden="true" tabindex="-1"></a>continent_pop_ag</span></code></pre></div>
<pre><code>## Simple feature collection with 8 features and 2 fields
## Attribute-geometry relationship: 0 constant, 1 aggregate, 1 identity
## Geometry type: GEOMETRY
## Dimension:     XY
## Bounding box:  xmin: -180 ymin: -90 xmax: 180 ymax: 83.64513
## Geodetic CRS:  WGS 84
##                   Group.1        pop                       geometry
## 1                  Africa 1154946633 MULTIPOLYGON (((-16.71373 1...
## 2              Antarctica          0 MULTIPOLYGON (((-180 -84.71...
## 3                    Asia 4311408059 MULTIPOLYGON (((27.19238 40...
## 4                  Europe  669036256 MULTIPOLYGON (((-177.6636 7...
## 5           North America  565028684 MULTIPOLYGON (((-169.5294 6...
## 6                 Oceania   37757833 MULTIPOLYGON (((-179.7933 -...
## 7 Seven seas (open ocean)          0 POLYGON ((68.935 -48.625, 6...
## 8           South America  412060811 MULTIPOLYGON (((-71.37525 -...</code></pre>
<p>You may find that package <code>dplyr</code> provides more flexible functions for us in terms of attribute features calculation in spatial analysis. Hence, it is very helpful to use package <code>sf</code> and <code>dplyr</code> together.</p>
</div>
<div id="spatial-aggregation" class="section level2" number="5.3">
<h2><span class="header-section-number">5.3</span> Spatial Aggregation</h2>
<p>Similar to attribute data aggregation introduced in the previous section, spatial aggregation can be done by function <code>aggregate()</code>. In attribute aggregation, the first parameter should be in class sf, while the second parameter <code>by=</code> is a list with non-spatial data. There is a little difference on the data imported in parameter <code>by=</code>, which the data should also contain geometry in spatial aggregation. Briefly to say, in function <code>aggregate(x, by=y)</code>, spatial aggregation is the geometry of the source (y) that defines how values in the target object (x) are grouped.</p>
<p>Take data nz and nz_height for example. We want to know the average height in each province of New Zealand. The code is shown below.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="spatial-operations.html#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">aggregate</span>(<span class="at">x=</span>nz_height, <span class="at">by=</span>nz, <span class="at">FUN=</span>mean)</span></code></pre></div>
<pre><code>## Simple feature collection with 16 features and 2 fields
## Geometry type: MULTIPOLYGON
## Dimension:     XY
## Bounding box:  xmin: 1090144 ymin: 4748537 xmax: 2089533 ymax: 6191874
## Projected CRS: NZGD2000 / New Zealand Transverse Mercator 2000
## First 10 features:
##    t50_fid elevation                       geometry
## 1       NA        NA MULTIPOLYGON (((1745493 600...
## 2       NA        NA MULTIPOLYGON (((1803822 590...
## 3  2408405  2734.333 MULTIPOLYGON (((1860345 585...
## 4       NA        NA MULTIPOLYGON (((2049387 583...
## 5       NA        NA MULTIPOLYGON (((2024489 567...
## 6       NA        NA MULTIPOLYGON (((2024489 567...
## 7       NA        NA MULTIPOLYGON (((1740438 571...
## 8  2408395  2777.000 MULTIPOLYGON (((1866732 566...
## 9       NA        NA MULTIPOLYGON (((1881590 548...
## 10 2368390  2889.455 MULTIPOLYGON (((1557042 531...</code></pre>
<p>As the result shows, all of attribute features of data nz_height (first parameter) are average value of each province. And the geometry is based on the spatial data in second parameter <code>by=</code>. You may find that the data we obtain are not perfect, since it does not contain the features in second parameter <code>by=</code>. Also, it does not make sense to calculate the average of all attribute features. For instance, variable “t50_fid” is the identity number of the highest points, it does not make sense to derive its mean.</p>
<p>In addition to function <code>aggregate()</code>, the same result can also be generated by function <code>group_by() %&gt;% summarise()</code> in <code>dplyr</code> The code and result are shown below.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="spatial-operations.html#cb13-1" aria-hidden="true" tabindex="-1"></a>ave_height<span class="ot">=</span><span class="fu">st_join</span>(nz, nz_height)<span class="sc">%&gt;%</span></span>
<span id="cb13-2"><a href="spatial-operations.html#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Name)<span class="sc">%&gt;%</span></span>
<span id="cb13-3"><a href="spatial-operations.html#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">elevation=</span><span class="fu">mean</span>(elevation, <span class="at">na.rm=</span>T))</span>
<span id="cb13-4"><a href="spatial-operations.html#cb13-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-5"><a href="spatial-operations.html#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="co"># plot the map of average height of each province</span></span>
<span id="cb13-6"><a href="spatial-operations.html#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(ave_height)<span class="sc">+</span></span>
<span id="cb13-7"><a href="spatial-operations.html#cb13-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="fu">aes</span>(<span class="at">fill=</span>elevation))<span class="sc">+</span></span>
<span id="cb13-8"><a href="spatial-operations.html#cb13-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_continuous</span>(<span class="at">low=</span><span class="st">&quot;#CEFFCE&quot;</span>, <span class="at">high=</span><span class="st">&quot;#006000&quot;</span>)<span class="sc">+</span></span>
<span id="cb13-9"><a href="spatial-operations.html#cb13-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text=</span><span class="fu">element_blank</span>(),</span>
<span id="cb13-10"><a href="spatial-operations.html#cb13-10" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.ticks=</span><span class="fu">element_blank</span>(),</span>
<span id="cb13-11"><a href="spatial-operations.html#cb13-11" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.title=</span><span class="fu">element_blank</span>(),</span>
<span id="cb13-12"><a href="spatial-operations.html#cb13-12" aria-hidden="true" tabindex="-1"></a>        <span class="at">panel.background=</span><span class="fu">element_blank</span>())</span></code></pre></div>
<p><img src="series_files/figure-html/aggregation_spatial_dplyr-1.png" width="1700" style="display: block; margin: auto;" /></p>
<p>We need to join two spatial data (nz is the target data, which should be placed in the first parameter). Then, group by the variable “Name” and summarize the mean value of elevation in each group. Though the code is longer than function <code>aggregate()</code>, <code>dplyr</code> shows a readable and clear code to do the spatial aggregation.</p>
<p>In this example, we can again find that use <code>dplyr</code> and <code>sf</code> package together might be a better method to do spatial aggregation.</p>
</div>
<div id="interpolation" class="section level2" number="5.4">
<h2><span class="header-section-number">5.4</span> Interpolation</h2>
<p>Interpolation is the process that calculate estimates from a source set of polygons to an overlapping but incongruent set of target polygons. Imagine that we want to derive the population in a specific area, which is defined by us. Since the boundary of study area we define does not align with the one of population data (most of the population data is based on the villages or Statistical Areas), we should use interpolation to produce estimates in this situation. The concept is simply illustrated in the figure below.</p>
<p><img src="graph/interpolation.png" width="100%" style="display: block; margin: auto;" /></p>
<p>In the figure above, the study area contains three districts whose population have been surveyed. It is covered by 40% of Area 1; 25% of Area 2; and 40% of Area 3. Population is the attribute assumed to be spatially extensive, and the sum is preserved. Hence, we can simply derive the total population of the study area based on the weight of each area: 1000* 40% + 800* 25% + 900* 40% = 960.</p>
<p>For the study area, there are 40% of it is Area 1; 33.3% of it is Area 2; 26.7% of it is Area 3. Density is spatially intensive instead, and the mean is preserved. Hence, we can simply derive the mean density of the study area based on the area weight of study area: 200/3* 40% + 40* 33.3% + 90* 26.7% = 64.</p>
<p>Package <code>sf</code> provides a function <code>st_interpolation_aw()</code> to conduct the interpolation. There are three parameters required in the function <code>st_interpolate_aw(x, to, extensive)</code>. The first parameter (x) is the object of simple features, for which we want to aggregate attributes. The second parameter (to) is the object of simple features with the target geometries. Parameter <code>extensive=</code> is the operation of data. If it is True, the attribute variables are assumed to be spatially extensive (like population) and the sum is preserved, otherwise, spatially intensive (like population density) and the mean is preserved.</p>
<p>Here, we use the data incongruent and aggregating_zones provided by package spData. The former one is a specific region separated into 9 districts in UK, while the latter is in the same region, but separated into 2 major area (as the figure shown below). We need to interpolate the value in data incongruent to the geometry data aggregating_zones, and derive the sum of value in two areas. The code and result are shown below.</p>
<p><img src="graph/aggregating_zones_incongruent.png" width="70%" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="spatial-operations.html#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_interpolate_aw</span>(incongruent[<span class="st">&quot;value&quot;</span>], aggregating_zones, <span class="at">extensive=</span>T)</span></code></pre></div>
<pre><code>## Warning in st_interpolate_aw.sf(incongruent[&quot;value&quot;], aggregating_zones, :
## st_interpolate_aw assumes attributes are constant or uniform over areas of x</code></pre>
<pre><code>## Simple feature collection with 2 features and 1 field
## Attribute-geometry relationship: 0 constant, 1 aggregate, 0 identity
## Geometry type: MULTIPOLYGON
## Dimension:     XY
## Bounding box:  xmin: 417686.2 ymin: 443703.6 xmax: 422959.3 ymax: 447036.8
## Projected CRS: OSGB 1936 / British National Grid
##      value                       geometry
## 1 19.61613 MULTIPOLYGON (((418731.9 44...
## 2 25.66872 MULTIPOLYGON (((419196.4 44...</code></pre>
</div>
<div id="unions" class="section level2" number="5.5">
<h2><span class="header-section-number">5.5</span> Unions</h2>
<p>Aggregation can dissolve the boundaries of touching polygons in the same group. And what is the behind scene of the function <code>aggregate()</code> and <code>group_by() %&gt;% summarise()</code>? They combine the geometries and eliminate the boundaries in the group by using function <code>st_union()</code>. In the example shown below, we filter the West part of Us states, and then union it by collecting all the geometries together.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="spatial-operations.html#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># filter the west of US states</span></span>
<span id="cb17-2"><a href="spatial-operations.html#cb17-2" aria-hidden="true" tabindex="-1"></a>us_west<span class="ot">=</span><span class="fu">filter</span>(us_states, REGION<span class="sc">==</span><span class="st">&quot;West&quot;</span>)</span>
<span id="cb17-3"><a href="spatial-operations.html#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(us_west)</span></code></pre></div>
<pre><code>## Simple feature collection with 6 features and 6 fields
## Geometry type: MULTIPOLYGON
## Dimension:     XY
## Bounding box:  xmin: -124.4096 ymin: 31.33224 xmax: -102.0422 ymax: 49.00091
## Geodetic CRS:  NAD83
##   GEOID       NAME REGION            AREA total_pop_10 total_pop_15
## 1    04    Arizona   West 295281.3 [km^2]      6246816      6641928
## 2    08   Colorado   West 269573.1 [km^2]      4887061      5278906
## 3    16      Idaho   West 216512.7 [km^2]      1526797      1616547
## 4    30    Montana   West 380829.2 [km^2]       973739      1014699
## 5    32     Nevada   West 286363.7 [km^2]      2633331      2798636
## 6    06 California   West 409747.1 [km^2]     36637290     38421464
##                         geometry
## 1 MULTIPOLYGON (((-114.7196 3...
## 2 MULTIPOLYGON (((-109.0501 4...
## 3 MULTIPOLYGON (((-116.916 45...
## 4 MULTIPOLYGON (((-116.0492 4...
## 5 MULTIPOLYGON (((-119.9992 4...
## 6 MULTIPOLYGON (((-118.6034 3...</code></pre>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="spatial-operations.html#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># union us_west</span></span>
<span id="cb19-2"><a href="spatial-operations.html#cb19-2" aria-hidden="true" tabindex="-1"></a>us_west<span class="ot">=</span><span class="fu">st_union</span>(us_west)</span></code></pre></div>
<pre><code>## although coordinates are longitude/latitude, st_union assumes that they are planar</code></pre>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="spatial-operations.html#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(us_west)</span></code></pre></div>
<pre><code>## Geometry set for 1 feature 
## Geometry type: MULTIPOLYGON
## Dimension:     XY
## Bounding box:  xmin: -124.7042 ymin: 31.33224 xmax: -102.0422 ymax: 49.00236
## Geodetic CRS:  NAD83</code></pre>
<pre><code>## MULTIPOLYGON (((-124.411 42.25055, -124.4351 42...</code></pre>
<p><img src="series_files/figure-html/union_figure-1.png" width="1360" style="display: block; margin: auto;" /></p>
</div>
<div id="centroid" class="section level2" number="5.6">
<h2><span class="header-section-number">5.6</span> Centroid</h2>
<p>Centroid operations identify the center of the geographic objects. By using centroid, we can approximately estimate the distance between polygons. Or imagine you want to transform the complex polygon to the point geometry, centroid of the polygon may be a good choice. The most common type of centroid is called geographic centroid, which represents the center of mass in a spatial object. Function <code>st_centroid()</code> can generate the centroid. Use data us_states for example to derive the centroids of each states.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="spatial-operations.html#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># derive the centroid</span></span>
<span id="cb24-2"><a href="spatial-operations.html#cb24-2" aria-hidden="true" tabindex="-1"></a>us_states_centroid<span class="ot">=</span><span class="fu">st_centroid</span>(us_states)</span></code></pre></div>
<pre><code>## Warning in st_centroid.sf(us_states): st_centroid assumes attributes are
## constant over geometries of x</code></pre>
<pre><code>## Warning in st_centroid.sfc(st_geometry(x), of_largest_polygon =
## of_largest_polygon): st_centroid does not give correct centroids for longitude/
## latitude data</code></pre>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="spatial-operations.html#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot the map</span></span>
<span id="cb27-2"><a href="spatial-operations.html#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(us_states)<span class="sc">+</span></span>
<span id="cb27-3"><a href="spatial-operations.html#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>()<span class="sc">+</span></span>
<span id="cb27-4"><a href="spatial-operations.html#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data=</span>us_states_centroid, <span class="at">color=</span><span class="st">&quot;red&quot;</span>)<span class="sc">+</span></span>
<span id="cb27-5"><a href="spatial-operations.html#cb27-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text=</span><span class="fu">element_blank</span>(),</span>
<span id="cb27-6"><a href="spatial-operations.html#cb27-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.ticks=</span><span class="fu">element_blank</span>(),</span>
<span id="cb27-7"><a href="spatial-operations.html#cb27-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.title=</span><span class="fu">element_blank</span>(),</span>
<span id="cb27-8"><a href="spatial-operations.html#cb27-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">panel.background=</span><span class="fu">element_blank</span>())</span></code></pre></div>
<p><img src="series_files/figure-html/cemtroid_us_states-1.png" width="1200" style="display: block; margin: auto;" /></p>
<p>But there is a drawback of <code>st_centroid()</code>. If the polygon contains many separated areas, the centroid might not lie on the polygon. For instance, the centroid of the group islands may not be situated in the land of the island, but in the ocean. Function <code>st_point_on_surface</code> can solve this problem. It ensures that all of the points will fall in their parent object. But please note that the point <code>st_point_on_surface</code> generates does not guarantee to be located in the most largest area. Here comes an example about the centroid and point of surface on Penghu Island, which is located in 50 kilometers west of Taiwan Island. <font color="red"><em><em>Data needed has been downloaded previously. You placed the file in the same directory as the R script file.</em></em> Click <a href="https://drive.google.com/uc?export=download&amp;id=1TSavur6YcaJO5DCCb5Hsb0HICdwZpeXi"><strong>here</strong></a> to re-download the file if it is lost.</font></p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="spatial-operations.html#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># read the shapefile of Taiwan and filter Penghu Island</span></span>
<span id="cb28-2"><a href="spatial-operations.html#cb28-2" aria-hidden="true" tabindex="-1"></a>taiwan_county<span class="ot">=</span><span class="fu">read_sf</span>(<span class="st">&quot;./data/taiwan_county/taiwan_county.shp&quot;</span>)</span>
<span id="cb28-3"><a href="spatial-operations.html#cb28-3" aria-hidden="true" tabindex="-1"></a>penghu<span class="ot">=</span><span class="fu">filter</span>(taiwan_county, COUNTYCODE<span class="sc">==</span><span class="dv">10016</span>)</span>
<span id="cb28-4"><a href="spatial-operations.html#cb28-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-5"><a href="spatial-operations.html#cb28-5" aria-hidden="true" tabindex="-1"></a><span class="co"># derive the centroid</span></span>
<span id="cb28-6"><a href="spatial-operations.html#cb28-6" aria-hidden="true" tabindex="-1"></a>penghu_centroid<span class="ot">=</span><span class="fu">st_centroid</span>(penghu)</span></code></pre></div>
<pre><code>## Warning in st_centroid.sf(penghu): st_centroid assumes attributes are constant
## over geometries of x</code></pre>
<pre><code>## Warning in st_centroid.sfc(st_geometry(x), of_largest_polygon =
## of_largest_polygon): st_centroid does not give correct centroids for longitude/
## latitude data</code></pre>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="spatial-operations.html#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># derive the point on surface</span></span>
<span id="cb31-2"><a href="spatial-operations.html#cb31-2" aria-hidden="true" tabindex="-1"></a>penghu_point<span class="ot">=</span><span class="fu">st_point_on_surface</span>(penghu)</span></code></pre></div>
<pre><code>## Warning in st_point_on_surface.sf(penghu): st_point_on_surface assumes
## attributes are constant over geometries of x</code></pre>
<pre><code>## Warning in st_point_on_surface.sfc(st_geometry(x)): st_point_on_surface may not
## give correct results for longitude/latitude data</code></pre>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="spatial-operations.html#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot the map</span></span>
<span id="cb34-2"><a href="spatial-operations.html#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(penghu)<span class="sc">+</span></span>
<span id="cb34-3"><a href="spatial-operations.html#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>()<span class="sc">+</span></span>
<span id="cb34-4"><a href="spatial-operations.html#cb34-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data=</span>penghu_point, <span class="at">color=</span><span class="st">&quot;red&quot;</span>, <span class="at">size=</span><span class="dv">2</span>)<span class="sc">+</span></span>
<span id="cb34-5"><a href="spatial-operations.html#cb34-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data=</span>penghu_centroid, <span class="at">color=</span><span class="st">&quot;blue&quot;</span>, <span class="at">size=</span><span class="dv">2</span>)<span class="sc">+</span></span>
<span id="cb34-6"><a href="spatial-operations.html#cb34-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text=</span><span class="fu">element_blank</span>(),</span>
<span id="cb34-7"><a href="spatial-operations.html#cb34-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.ticks=</span><span class="fu">element_blank</span>(),</span>
<span id="cb34-8"><a href="spatial-operations.html#cb34-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.title=</span><span class="fu">element_blank</span>(),</span>
<span id="cb34-9"><a href="spatial-operations.html#cb34-9" aria-hidden="true" tabindex="-1"></a>        <span class="at">panel.background=</span><span class="fu">element_blank</span>())</span></code></pre></div>
<p><img src="series_files/figure-html/point_on_surface-1.png" width="360" style="display: block; margin: auto;" /></p>
<p>In Penghu example, we can find that the point on surface (red dot) and the centroid (blue dot) are not the same. Centroid is located in the inland sea of Penghu, while the point on surface is located in one of the island of Penghu. Please note that the island which point on surface located in is not the largest one. For more information of its algorithm, please refer to the <a href="https://gis.stackexchange.com/questions/76498/how-is-st-pointonsurface-calculated">discussion</a> attached.</p>
</div>
<div id="buffer" class="section level2" number="5.7">
<h2><span class="header-section-number">5.7</span> Buffer</h2>
<p>Imagine that we want to calculate the number of schools within 500 meters radius of MRT stations, we need to first draw the buffer of each MRT stations before points calculation. Buffer is a zone (polygon) around a map feature within given distance, and it is useful for proximity analysis. Buffer can be created by function <code>st_buffer()</code>, whatever the type of geometry is. There are two parameters should be filled in <code>st_buffer()</code>. Place the spatial data first, and then set the distance of radius. But please note that the unit of distance is based on the coordinate reference system. In general, the unit is meter (m) in the <a href="basic-knowledge-on-gis.html#coordinate-reference-system-crs">projected coordinate system</a>, while the unit is NULL in the the geographic coordinate systems (e.g., EPSG:4326). Hence, we need to use function <a href="geographic-data.html#reproject-geographic-data"><code>st_transform()</code></a> to convert CRS to specific projected coordinate system in the region of study area, if the spatial data with CRS EPSG:4326 is obtained.</p>
<p>Examples below illustrates the buffer of cycle hire points across London. Data cycle hire is provided by package spData. Suppose we define the region within 300 meters of hire points is service area.</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="spatial-operations.html#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># test of the CRS and buffer of cycle_hire</span></span>
<span id="cb35-2"><a href="spatial-operations.html#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">st_crs</span>(cycle_hire)<span class="sc">$</span>epsg             <span class="co"># original CRS: EPSG:4326 (geographic)</span></span></code></pre></div>
<pre><code>## [1] 4326</code></pre>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="spatial-operations.html#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_crs</span>(cycle_hire)<span class="sc">$</span>units            <span class="co"># units: NULL</span></span></code></pre></div>
<pre><code>## NULL</code></pre>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="spatial-operations.html#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_buffer</span>(cycle_hire, <span class="dv">300</span>)</span></code></pre></div>
<pre><code>## Warning in st_buffer.sfc(st_geometry(x), dist, nQuadSegs, endCapStyle =
## endCapStyle, : st_buffer does not correctly buffer longitude/latitude data</code></pre>
<pre><code>## dist is assumed to be in decimal degrees (arc_degrees).</code></pre>
<pre><code>## Simple feature collection with 742 features and 5 fields
## Geometry type: POLYGON
## Dimension:     XY
## Bounding box:  xmin: -300.2368 ymin: -248.5452 xmax: 299.9977 ymax: 351.5421
## Geodetic CRS:  WGS 84
## First 10 features:
##    id               name             area nbikes nempty
## 1   1       River Street      Clerkenwell      4     14
## 2   2 Phillimore Gardens       Kensington      2     34
## 3   3 Christopher Street Liverpool Street      0     32
## 4   4  St. Chad&#39;s Street     King&#39;s Cross      4     19
## 5   5     Sedding Street    Sloane Square     15     12
## 6   6 Broadcasting House       Marylebone      0     18
## 7   7   Charlbert Street  St. John&#39;s Wood     15      0
## 8   8         Lodge Road  St. John&#39;s Wood      5     13
## 9   9     New Globe Walk         Bankside      3     16
## 10 10        Park Street         Bankside      1     17
##                          geometry
## 1  POLYGON ((299.89 51.52916, ...
## 2  POLYGON ((299.8024 51.49961...
## 3  POLYGON ((299.9154 51.52128...
## 4  POLYGON ((299.879 51.53006,...
## 5  POLYGON ((299.8431 51.49313...
## 6  POLYGON ((299.8558 51.51812...
## 7  POLYGON ((299.8319 51.5343,...
## 8  POLYGON ((299.8299 51.52834...
## 9  POLYGON ((299.9036 51.50739...
## 10 POLYGON ((299.9072 51.50597...</code></pre>
<p>The warning shows that <code>st_buffer()</code> does not correctly buffer longitude-latitude spatial data, whose distance is assumed to be in decimal degrees (arc_degrees). Though the operation of geometry is still done, it is not true. (You can plot the map to check what the geometry looks like.) Hence, we should not use the spatial data with EPSG:4326 to create buffer, but transform CRS in advance. However, what CRS should be applied? We can look up the CRS of England in <a href="https://epsg.io/?q=England">EPSG database</a>.</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="spatial-operations.html#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># transform CRS to EPSG:27700 (projected)</span></span>
<span id="cb43-2"><a href="spatial-operations.html#cb43-2" aria-hidden="true" tabindex="-1"></a>cycle_hire_new<span class="ot">=</span><span class="fu">st_transform</span>(cycle_hire, <span class="at">crs=</span><span class="dv">27700</span>)</span>
<span id="cb43-3"><a href="spatial-operations.html#cb43-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-4"><a href="spatial-operations.html#cb43-4" aria-hidden="true" tabindex="-1"></a><span class="co"># create the buffer (radius: 300 m)</span></span>
<span id="cb43-5"><a href="spatial-operations.html#cb43-5" aria-hidden="true" tabindex="-1"></a><span class="fu">st_buffer</span>(cycle_hire_new, <span class="dv">300</span>)</span></code></pre></div>
<pre><code>## Simple feature collection with 742 features and 5 fields
## Geometry type: POLYGON
## Dimension:     XY
## Bounding box:  xmin: 522202 ymin: 174108 xmax: 539033.2 ymax: 184721
## Projected CRS: OSGB 1936 / British National Grid
## First 10 features:
##    id               name             area nbikes nempty
## 1   1       River Street      Clerkenwell      4     14
## 2   2 Phillimore Gardens       Kensington      2     34
## 3   3 Christopher Street Liverpool Street      0     32
## 4   4  St. Chad&#39;s Street     King&#39;s Cross      4     19
## 5   5     Sedding Street    Sloane Square     15     12
## 6   6 Broadcasting House       Marylebone      0     18
## 7   7   Charlbert Street  St. John&#39;s Wood     15      0
## 8   8         Lodge Road  St. John&#39;s Wood      5     13
## 9   9     New Globe Walk         Bankside      3     16
## 10 10        Park Street         Bankside      1     17
##                          geometry
## 1  POLYGON ((531503.5 182832.1...
## 2  POLYGON ((525508.1 179391.9...
## 3  POLYGON ((533285.8 182001.6...
## 4  POLYGON ((530737.8 182912, ...
## 5  POLYGON ((528351 178742, 52...
## 6  POLYGON ((529158.4 181542.9...
## 7  POLYGON ((527459 183300.8, ...
## 8  POLYGON ((527332.7 182634.6...
## 9  POLYGON ((532505 180434.6, ...
## 10 POLYGON ((532764.9 180284.3...</code></pre>
<p><img src="series_files/figure-html/buffer_figure-1.png" width="660" style="display: block; margin: auto;" /></p>
<p>Figure above shows the location of cycle hire points (black dots), and the buffer of each point is painted blue.</p>
</div>
<div id="boundary" class="section level2" number="5.8">
<h2><span class="header-section-number">5.8</span> Boundary</h2>
<p>Function <code>st_boundary()</code> creates a polygon that encompasses the full extent of the geometry. Boundary and union are often applied together to emphasize the border of the study area. The example below shows the us_state and makes the border of country thicker.</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="spatial-operations.html#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># union us_states and then derive the boundary</span></span>
<span id="cb45-2"><a href="spatial-operations.html#cb45-2" aria-hidden="true" tabindex="-1"></a>us_boundary<span class="ot">=</span><span class="fu">st_boundary</span>(<span class="fu">st_union</span>(us_states))</span></code></pre></div>
<pre><code>## although coordinates are longitude/latitude, st_union assumes that they are planar</code></pre>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="spatial-operations.html#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot the map</span></span>
<span id="cb47-2"><a href="spatial-operations.html#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(us_states)<span class="sc">+</span></span>
<span id="cb47-3"><a href="spatial-operations.html#cb47-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>()<span class="sc">+</span></span>
<span id="cb47-4"><a href="spatial-operations.html#cb47-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data=</span>us_boundary, <span class="at">size=</span><span class="dv">1</span>)<span class="sc">+</span></span>
<span id="cb47-5"><a href="spatial-operations.html#cb47-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text=</span><span class="fu">element_blank</span>(),</span>
<span id="cb47-6"><a href="spatial-operations.html#cb47-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.ticks=</span><span class="fu">element_blank</span>(),</span>
<span id="cb47-7"><a href="spatial-operations.html#cb47-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.title=</span><span class="fu">element_blank</span>(),</span>
<span id="cb47-8"><a href="spatial-operations.html#cb47-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">panel.background=</span><span class="fu">element_blank</span>())</span></code></pre></div>
<p><img src="series_files/figure-html/boundary-1.png" width="540" style="display: block; margin: auto;" /></p>
</div>
<div id="clipping" class="section level2" number="5.9">
<h2><span class="header-section-number">5.9</span> Clipping</h2>
<p>Clipping is a critical spatial operation in GIS. It extracts the geometry (point, line, polygon) that lies within the area outlined by the clip polygon. For instance, we have polygon of Taipei City and points of schools in Taiwan, and suppose we want to extract the schools located in Taipei City. We need to use the polygon to clip the point data, removing all the points outside the polygon. Though there is no “clip” function provided by package <code>sf</code> in fact, function <code>st_intersection()</code> help us do so. But please note that there is a difference between clipping and intersection in an accurate GIS definition. Clipping and intersection both extracts the geometry in a specific polygon; nonetheless, clipping does not retain the attributes of the clip polygon, while intersection creates output features which possess the attributes of all input features. The concept is illustrated below.</p>
<p><img src="graph/clip_intersection.png" width="90%" style="display: block; margin: auto;" /></p>
<p>The slight difference may be a fundamental concept of GIS, but it is not really vital in terms of spatial analysis in R (after all, there is no clip function provided in R). In <code>st_intersection(x, y)</code>, it is free to place the spatial data in two parameters. But please note data x would be on the left-hand side of new data frame, while y is on the right-hand side. Here we use the example of nz (map of New Zealand) and nz_height (101 highest point in New Zealand) again. Suppose we want to extract the points located in North Island, the code and result are shown below.</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="spatial-operations.html#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># filter North Island in data nz</span></span>
<span id="cb48-2"><a href="spatial-operations.html#cb48-2" aria-hidden="true" tabindex="-1"></a>nz_north<span class="ot">=</span><span class="fu">filter</span>(nz, Island<span class="sc">==</span><span class="st">&quot;North&quot;</span>)</span>
<span id="cb48-3"><a href="spatial-operations.html#cb48-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-4"><a href="spatial-operations.html#cb48-4" aria-hidden="true" tabindex="-1"></a><span class="co"># st_intersection(point, polygon)</span></span>
<span id="cb48-5"><a href="spatial-operations.html#cb48-5" aria-hidden="true" tabindex="-1"></a><span class="fu">st_intersection</span>(nz_height, nz_north)</span></code></pre></div>
<pre><code>## Warning: attribute variables are assumed to be spatially constant throughout all
## geometries</code></pre>
<pre><code>## Simple feature collection with 5 features and 8 fields
## Geometry type: POINT
## Dimension:     XY
## Bounding box:  xmin: 1820643 ymin: 5647971 xmax: 1822492 ymax: 5650492
## Projected CRS: NZGD2000 / New Zealand Transverse Mercator 2000
##     t50_fid elevation              Name Island Land_area Population
## 99  2408397      2751           Waikato  North  23900.04     460100
## 100 2408406      2720           Waikato  North  23900.04     460100
## 101 2408411      2732           Waikato  North  23900.04     460100
## 97  2408394      2797 Manawatu-Wanganui  North  22220.61     234500
## 98  2408395      2757 Manawatu-Wanganui  North  22220.61     234500
##     Median_income Sex_ratio                geometry
## 99          27900 0.9520500 POINT (1820660 5649488)
## 100         27900 0.9520500 POINT (1822263 5650429)
## 101         27900 0.9520500 POINT (1822492 5650492)
## 97          25000 0.9387734 POINT (1821014 5647971)
## 98          25000 0.9387734 POINT (1820643 5648331)</code></pre>
<p>Remember the spatial join operation? Actually, we can use function <a href="spatial-operations.html#spatial-join"><code>st_join()</code></a> to do the same thing. The code is shown below.</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="spatial-operations.html#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># union two data first</span></span>
<span id="cb51-2"><a href="spatial-operations.html#cb51-2" aria-hidden="true" tabindex="-1"></a>nz_height_join<span class="ot">=</span><span class="fu">st_join</span>(nz_height, nz)</span>
<span id="cb51-3"><a href="spatial-operations.html#cb51-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-4"><a href="spatial-operations.html#cb51-4" aria-hidden="true" tabindex="-1"></a><span class="co"># filter the highest point located in North Island</span></span>
<span id="cb51-5"><a href="spatial-operations.html#cb51-5" aria-hidden="true" tabindex="-1"></a><span class="fu">filter</span>(nz_height_join, Island<span class="sc">==</span><span class="st">&quot;North&quot;</span>)</span></code></pre></div>
<pre><code>## Simple feature collection with 5 features and 8 fields
## Geometry type: POINT
## Dimension:     XY
## Bounding box:  xmin: 1820643 ymin: 5647971 xmax: 1822492 ymax: 5650492
## Projected CRS: NZGD2000 / New Zealand Transverse Mercator 2000
##   t50_fid elevation              Name Island Land_area Population Median_income
## 1 2408394      2797 Manawatu-Wanganui  North  22220.61     234500         25000
## 2 2408395      2757 Manawatu-Wanganui  North  22220.61     234500         25000
## 3 2408397      2751           Waikato  North  23900.04     460100         27900
## 4 2408406      2720           Waikato  North  23900.04     460100         27900
## 5 2408411      2732           Waikato  North  23900.04     460100         27900
##   Sex_ratio                geometry
## 1 0.9387734 POINT (1821014 5647971)
## 2 0.9387734 POINT (1820643 5648331)
## 3 0.9520500 POINT (1820660 5649488)
## 4 0.9520500 POINT (1822263 5650429)
## 5 0.9520500 POINT (1822492 5650492)</code></pre>
<p>In this example, we find that function <code>st_join()</code> and <code>st_intersection()</code> do the similar operation. This is because that <code>st_join()</code> sets the operation to “intersection” by default, that is, the parameter is <code>st_join(..., join="st_intersects")</code>. Other operations are listed in the table of <a href="spatial-operations.html#geos_binary_pred"><code>geos_binary_pred</code></a>.</p>
<p>In addition to <code>st_intersection</code>, there are some functions to do subsetting and clipping spatial data. To illustrate the concept and operations of these functions, we use a simple example: two overlapping circles (X and Y), with a center point one unit away from each other and a radius of one. The code and results are shown below.</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="spatial-operations.html#cb53-1" aria-hidden="true" tabindex="-1"></a>X<span class="ot">=</span><span class="fu">st_buffer</span>(<span class="fu">st_point</span>(<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>)), <span class="at">dist=</span><span class="dv">1</span>)</span>
<span id="cb53-2"><a href="spatial-operations.html#cb53-2" aria-hidden="true" tabindex="-1"></a>Y<span class="ot">=</span><span class="fu">st_buffer</span>(<span class="fu">st_point</span>(<span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">1</span>)), <span class="at">dist=</span><span class="dv">1</span>)</span>
<span id="cb53-3"><a href="spatial-operations.html#cb53-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-4"><a href="spatial-operations.html#cb53-4" aria-hidden="true" tabindex="-1"></a><span class="fu">st_intersection</span>(X, Y)</span>
<span id="cb53-5"><a href="spatial-operations.html#cb53-5" aria-hidden="true" tabindex="-1"></a><span class="fu">st_difference</span>(X, Y)</span>
<span id="cb53-6"><a href="spatial-operations.html#cb53-6" aria-hidden="true" tabindex="-1"></a><span class="fu">st_difference</span>(Y, X)</span>
<span id="cb53-7"><a href="spatial-operations.html#cb53-7" aria-hidden="true" tabindex="-1"></a><span class="fu">st_union</span>(X, Y)</span>
<span id="cb53-8"><a href="spatial-operations.html#cb53-8" aria-hidden="true" tabindex="-1"></a><span class="fu">st_sym_difference</span>(X, Y)</span></code></pre></div>
<p><img src="series_files/figure-html/clip_operation_figure-1.png" width="900" style="display: block; margin: auto;" /></p>
</div>
<div id="simplification" class="section level2" number="5.10">
<h2><span class="header-section-number">5.10</span> Simplification</h2>
<p>When plotting the map, it is better to remove the detailed data and trivial information which may make the map complicated. This process is called cartographic generalization. It seeks to abstract spatial information at a high level of detail to information that can be rendered on a map at a lower level of detail. One of the main type of generalization is simplification. It simplifies the geometry, and result in reducing the amount of memory. To do simplification, many algorithms have been developed, such as <a href="https://www.wikiwand.com/en/Ramer%E2%80%93Douglas%E2%80%93Peucker_algorithm">Ramer–Douglas–Peucker algorithm</a> and <a href="https://www.wikiwand.com/en/Visvalingam%E2%80%93Whyatt_algorithm">Visvalingam–Whyatt algorithm</a>. Let’s take a closer look on Ramer–Douglas–Peucker algorithm illustrated in the figure below.</p>
<p><img src="graph/simplification.gif"></p>
<p>The algorithm initially finds the point that is farthest from the line segment with the first and last points as end points. If the distance between the point and line segment is shorter than the minimum threshold ε, then any other points can be discarded. If the distance is greater than ε, the point must be kept. The algorithm recursively calls itself with the first point and the farthest point and then with the farthest point and the last point, which includes the farthest point being marked as kept.</p>
<p>Function <code>st_simplify()</code> provided in package <code>sf</code> can do so. The simplification operation can be applied on all of the geometries (point, line, polygon). In function <code>st_simplify(x, dTolerance)</code>, spatial data is placed in the first parameter (x). Parameter <code>dTolerance</code> represents the minimum threshold (ε). Please note that the spatial data should be in projected coordinate system, or it might cause error. We can use function <code>st_crs()$unit</code> to confirm whether the unit is “meter.” If it is NULL, it represents the data is in geographic coordinate system, please look up the appropriate CRS in <a href="https://epsg.io/">EPSG database</a>. Here, let’s simplify the map of US states as code shown below.</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="spatial-operations.html#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># check the unit (if NULL, convert CRS)</span></span>
<span id="cb54-2"><a href="spatial-operations.html#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="fu">st_crs</span>(us_states)<span class="sc">$</span>units</span></code></pre></div>
<pre><code>## NULL</code></pre>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="spatial-operations.html#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># transform CRS to 2163</span></span>
<span id="cb56-2"><a href="spatial-operations.html#cb56-2" aria-hidden="true" tabindex="-1"></a>us_states_2163<span class="ot">=</span><span class="fu">st_transform</span>(us_states, <span class="at">crs=</span><span class="dv">2163</span>)</span>
<span id="cb56-3"><a href="spatial-operations.html#cb56-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-4"><a href="spatial-operations.html#cb56-4" aria-hidden="true" tabindex="-1"></a><span class="co"># simplification (ε = 100000 meters = 100 kilometers)</span></span>
<span id="cb56-5"><a href="spatial-operations.html#cb56-5" aria-hidden="true" tabindex="-1"></a><span class="fu">st_simplify</span>(us_states_2163, <span class="at">dTolerance=</span><span class="dv">100000</span>)</span></code></pre></div>
<pre><code>## Simple feature collection with 49 features and 6 fields (with 5 geometries empty)
## Geometry type: GEOMETRY
## Dimension:     XY
## Bounding box:  xmin: -1970356 ymin: -2112380 xmax: 2521545 ymax: 731357.6
## Projected CRS: NAD27 / US National Atlas Equal Area
## First 10 features:
##    GEOID        NAME   REGION             AREA total_pop_10 total_pop_15
## 1     01     Alabama    South 133709.27 [km^2]      4712651      4830620
## 2     04     Arizona     West 295281.25 [km^2]      6246816      6641928
## 3     08    Colorado     West 269573.06 [km^2]      4887061      5278906
## 4     09 Connecticut Norteast  12976.59 [km^2]      3545837      3593222
## 5     12     Florida    South 151052.01 [km^2]     18511620     19645772
## 6     13     Georgia    South 152725.21 [km^2]      9468815     10006693
## 7     16       Idaho     West 216512.66 [km^2]      1526797      1616547
## 8     18     Indiana  Midwest  93648.40 [km^2]      6417398      6568645
## 9     20      Kansas  Midwest 213037.08 [km^2]      2809329      2892987
## 10    22   Louisiana    South 122345.76 [km^2]      4429940      4625253
##                          geometry
## 1  POLYGON ((1076896 -1034555,...
## 2  POLYGON ((-1379163 -1242190...
## 3  POLYGON ((-759892.8 -402580...
## 4  POLYGON ((2148004 24195.53,...
## 5  POLYGON ((1433831 -1425453,...
## 6  POLYGON ((1311335 -999185, ...
## 7  POLYGON ((-1298505 247303.5...
## 8  POLYGON ((1033794 -287181.6...
## 9  POLYGON ((-175289.2 -552753...
## 10 POLYGON ((558984.4 -1308375...</code></pre>
<p><img src="series_files/figure-html/simplification_result-1.png" width="1360" style="display: block; margin: auto;" /></p>
</div>
<div id="affine-transformations" class="section level2" number="5.11">
<h2><span class="header-section-number">5.11</span> Affine Transformations</h2>
<p>Affine transformation is a geometric transformation that preserves lines and parallelism, but might change length or angle. It includes shifting, scaling and rotation. Affine transformation is usually used to improve map visualization, or to revise the distorted projected map. Contents below illustrates the codes and results of three basic transformations by using spatial data <code>us_states</code>.</p>
<p>Before conducting affine transformation, please ensure that the data should be based on projected coordinate system, namely the unit is “meter.” In previous section, we knew that <code>us_states</code> is in geographic coordinate system, and hence, we should transform CRS to the projected one (EPSG:2163).</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="spatial-operations.html#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="co"># transform CRS to 2163</span></span>
<span id="cb58-2"><a href="spatial-operations.html#cb58-2" aria-hidden="true" tabindex="-1"></a>us_states_2163<span class="ot">=</span><span class="fu">st_transform</span>(us_states, <span class="at">crs=</span><span class="dv">2163</span>)</span></code></pre></div>
<p>In addition, the transformation is implemented on the <a href="geographic-data.html#simple-feature-geometries-sfg">sfg</a> and <a href="geographic-data.html#simple-feature-columns-sfc">sfc</a> object, instead of <a href="geographic-data.html#simple-feature-sf">sf</a> (the whole spatial data). Thus, please conduct the transformation on the geometry column in spatial data, such as the form <code>DATA$geometry</code>. <code>DATA</code> means the spatial data (sf), and use <code>$</code> to retrieve the <code>geometry</code> (sfc) in the data.</p>
<p>Shifting moves every point by the same distance in map units. It can be simply achieved by adding vector object after the spatial data. For instance, in the example below, we shift all x-coordinate by 500,000 meters to the east, while shift all y-coordinate 300,000 meters to the south.</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="spatial-operations.html#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co"># shift the map</span></span>
<span id="cb59-2"><a href="spatial-operations.html#cb59-2" aria-hidden="true" tabindex="-1"></a>us_states_shift<span class="ot">=</span>us_states_2163<span class="sc">$</span>geometry<span class="sc">+</span><span class="fu">c</span>(<span class="dv">500000</span>,<span class="sc">-</span><span class="dv">300000</span>)</span></code></pre></div>
<p><img src="series_files/figure-html/us_states_shift_map-1.png" width="450" style="display: block; margin: auto;" /></p>
<p>Scaling enlarges or shrinks objects by a factor. There are two types of scaling, global and local. Global scaling increases or decreases all coordinate values in relation to the origin coordinates (0,0), while keeping all geometries topological relations intact. It can be done by multiplying a factor on sfg or sfc object. Local scaling is based on each fixed specific point (e.g, centroid), and multiply the scaling factor by the distance of the geometries to the specific point. The concept of global and local scaling are illustrated as figure below.</p>
<p><img src="graph/scale.png" width="70%" style="display: block; margin: auto;" /></p>
<p>The following code and result show the <strong>global scaling</strong> (shrink) of us_states.</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="spatial-operations.html#cb60-1" aria-hidden="true" tabindex="-1"></a>us_states_scale<span class="ot">=</span>us_states_2163<span class="sc">$</span>geometry<span class="sc">/</span><span class="dv">2</span></span></code></pre></div>
<p><img src="series_files/figure-html/us_states_scale_map_1-1.png" width="450" style="display: block; margin: auto;" /></p>
<p>The following code and result show the <strong>local scaling</strong> (shrink) of us_states.</p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="spatial-operations.html#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="co"># find the centroid first</span></span>
<span id="cb61-2"><a href="spatial-operations.html#cb61-2" aria-hidden="true" tabindex="-1"></a>us_states_centroid<span class="ot">=</span><span class="fu">st_centroid</span>(us_states_2163)</span>
<span id="cb61-3"><a href="spatial-operations.html#cb61-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-4"><a href="spatial-operations.html#cb61-4" aria-hidden="true" tabindex="-1"></a><span class="co"># new point = (vector of geometry to centroid) * factor + centroid</span></span>
<span id="cb61-5"><a href="spatial-operations.html#cb61-5" aria-hidden="true" tabindex="-1"></a>us_states_scale<span class="ot">=</span>(us_states_2163<span class="sc">$</span>geometry<span class="sc">-</span>us_states_centroid<span class="sc">$</span>geometry)<span class="sc">/</span><span class="fl">1.3</span><span class="sc">+</span>us_states_centroid<span class="sc">$</span>geometry</span></code></pre></div>
<p><img src="series_files/figure-html/us_states_scale_map_2-1.png" width="450" style="display: block; margin: auto;" /></p>
<p>Rotation in two-dimensional coordinate can be done by the rotation matrix shown below. It rotates geometry in a counterclockwise direction.</p>
<p><img src="graph/rotation_matrix.png" width="20%" style="display: block; margin: auto;" /></p>
<p>The rotation function is listed as follows.</p>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="spatial-operations.html#cb62-1" aria-hidden="true" tabindex="-1"></a>rotation<span class="ot">=</span><span class="cf">function</span>(x){</span>
<span id="cb62-2"><a href="spatial-operations.html#cb62-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># covert degree to radian</span></span>
<span id="cb62-3"><a href="spatial-operations.html#cb62-3" aria-hidden="true" tabindex="-1"></a>  r<span class="ot">=</span>x<span class="sc">*</span>pi<span class="sc">/</span><span class="dv">180</span></span>
<span id="cb62-4"><a href="spatial-operations.html#cb62-4" aria-hidden="true" tabindex="-1"></a>  <span class="co"># rotation matrix</span></span>
<span id="cb62-5"><a href="spatial-operations.html#cb62-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="fu">cos</span>(r), <span class="fu">sin</span>(r), <span class="sc">-</span><span class="fu">sin</span>(r), <span class="fu">cos</span>(r)), <span class="at">nrow=</span><span class="dv">2</span>, <span class="at">ncol=</span><span class="dv">2</span>)</span>
<span id="cb62-6"><a href="spatial-operations.html#cb62-6" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p>Rotation could be done around a specific point. The vector generated by the geometries and specific point should multiply by the rotation matrix, and then add the coordinate of specific point to derive the coordinate of geometries after rotation. Detailed information of rotation matrix, please review <a href="https://www.wikiwand.com/en/Rotation_matrix">linear algebra</a>. The rotation of us_states is as follows.</p>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="spatial-operations.html#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="co"># find the centroid first</span></span>
<span id="cb63-2"><a href="spatial-operations.html#cb63-2" aria-hidden="true" tabindex="-1"></a>us_states_centroid<span class="ot">=</span><span class="fu">st_centroid</span>(us_states_2163)</span>
<span id="cb63-3"><a href="spatial-operations.html#cb63-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-4"><a href="spatial-operations.html#cb63-4" aria-hidden="true" tabindex="-1"></a><span class="co"># new point = (vector of geometry to centroid) * rotation matrix + centroid</span></span>
<span id="cb63-5"><a href="spatial-operations.html#cb63-5" aria-hidden="true" tabindex="-1"></a>us_states_rotation<span class="ot">=</span>(us_states_2163<span class="sc">$</span>geometry<span class="sc">-</span>us_states_centroid<span class="sc">$</span>geometry)<span class="sc">*</span><span class="fu">rotation</span>(<span class="dv">30</span>)<span class="sc">+</span>us_states_centroid<span class="sc">$</span>geometry</span></code></pre></div>
<p><img src="series_files/figure-html/us_states_rotation_map-1.png" width="450" style="display: block; margin: auto;" /></p>
</div>
<div id="geometric-measurement" class="section level2" number="5.12">
<h2><span class="header-section-number">5.12</span> Geometric Measurement</h2>
<p>Geometric measurement is mainly to measure the area, length and distance of the geometries. The operation can be done by the function <code>st_area</code>, <code>st_length</code> and <code>st_distance</code> in package <code>sf</code> respectively. Geometric measurement is very useful when it comes to calculating the population density (area), the radial distance between two points (distance) and lots of practical issues. But please note that the precision of the geometric measurement depends on the projection of the map (CRS). If we use the geographic coordinate systems (latitude–longitude, e.g., EPSG:4326) to measure the geometries, we may obtain a wrong result. This is because the geographic coordinate systems uses a three-dimensional spherical surface to define a location on the earth with longitudes and latitudes in degrees, and of course, the measurement on two-dimensional must result in the high deviation. The measurement of functions can be well-performed when the geometries in a correct projected coordinate system, which defines the X and Y of two-dimensional geometry. Here, we do not further discuss about the theory on the measurement difference among CRS, which requires better technical knowledge on the GIS, but just realize how to do calculation by using package <code>sf</code>.</p>
<p><code>st_area</code> is used to calculate the area of the polygon. Take data <code>lnd</code> in package <code>spData</code> for instance. <code>lnd</code> is the data that records all of the boroughs in London with the attributes such as name, official code, area, and so forth.</p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="spatial-operations.html#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">st_area</span>(lnd)</span></code></pre></div>
<pre><code>## Units: [m^2]
##  [1]  37275804  86520876 150170946  55950018  55567236 112367550 115753312
##  [8]  50484355  43249381  86779900  26818665  28870760  35158807  47345454
## [15]  60592248  82225772  38818676  56432387  43862148  57376438  37638114
## [22]  34276203  16403636  12128152  21494317  21796715  19783577  14861403
## [29]  19054716  29607835  36210825  36115169   2904829</code></pre>
<p>Simply place the data in the function <code>st_area()</code>, we would get the result. It shows the area of each borough in the sequence of the original data <code>lnd</code>, for example, the first row is Kingston upon Thames, and its area is 37275804 [m^2]. But is the result correct? We can then check the answer in the attribute fields of data <code>lnd</code>, which records the area in column named HECTARES. What’s surprising? The result are not identical. Column HECTARES in <code>lnd</code> tells us the area of Kingston upon Thames is 3726.117 [hectares], which is equal to 37261170 [m^2]; however, the result we get from <code>st_area</code> is 37275804 [m^2]. What’s our mistake?</p>
<p>The inconsistent results are derived from the wrong CRS we use. First of all, we can check the CRS of data <code>lnd</code>. Using function <code>st_crs()</code> to identify the coordinate system, we can find that the CRS is EPSG:4326 (geographic coordinate systems). As mentioned above, the geographic coordinate systems is defined in spherical surface, which is not appropriate to directly conduct geometric measurement. Hence, we need to convert it to coordinated system by function <a href="geographic-data.html#reproject-geographic-data"><code>st_transform</code></a> in advance, ensuring the precision of result. Please look up the CRS of London (England) in <a href="https://epsg.io/?q=England">EPSG database</a>.</p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="spatial-operations.html#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="co"># check out the CRS of lnd</span></span>
<span id="cb66-2"><a href="spatial-operations.html#cb66-2" aria-hidden="true" tabindex="-1"></a><span class="fu">st_crs</span>(lnd)<span class="sc">$</span>epsg</span></code></pre></div>
<pre><code>## [1] 4326</code></pre>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="spatial-operations.html#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The project coordinate system of England is 27700 </span></span>
<span id="cb68-2"><a href="spatial-operations.html#cb68-2" aria-hidden="true" tabindex="-1"></a>lnd_27700<span class="ot">=</span><span class="fu">st_transform</span>(lnd, <span class="at">crs=</span><span class="dv">27700</span>)</span>
<span id="cb68-3"><a href="spatial-operations.html#cb68-3" aria-hidden="true" tabindex="-1"></a><span class="fu">st_area</span>(lnd_27700)</span></code></pre></div>
<pre><code>## Units: [m^2]
##  [1]  37261178  86494436 150134858  55926233  55544350 112349669 115700544
##  [8]  50463301  43232640  86748314  26810042  28862036  35149085  47334073
## [15]  60580234  82200191  38807965  56419224  43846975  57353283  37624744
## [22]  34264163  16397618  12123848  21486977  21789296  19777937  14856653
## [29]  19049028  29598387  36201727  36107810   2903926</code></pre>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="spatial-operations.html#cb70-1" aria-hidden="true" tabindex="-1"></a>lnd_27700<span class="sc">$</span>HECTARES</span></code></pre></div>
<pre><code>##  [1]  3726.117  8649.441 15013.487  5658.541  5554.428 11445.735 11570.063
##  [8]  5046.330  4323.270  8674.837  2724.940  2991.340  3531.706  5044.190
## [15]  6428.649  8220.025  3880.793  5644.225  4384.698  5876.111  3762.466
## [22]  3522.022  1715.409  1238.379  2203.005  2178.932  2157.501  1485.664
## [29]  1904.902  2959.837  3857.806  3779.934   314.942</code></pre>
<p>Fortunately, we can derive a more precise area of each polygon. Please note that they are still not equal, possibly because of the problem of CRS issue again, but the difference between what we calculate and the attributes recorded (HECTARES) shrinks.</p>
<p>Length means to measure the length of a line, which can be operated by function <code>st_length()</code>. Take the perimeter of a country border for instance.</p>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="spatial-operations.html#cb72-1" aria-hidden="true" tabindex="-1"></a>lnd_27700_border<span class="ot">=</span><span class="fu">st_boundary</span>(lnd_27700)</span>
<span id="cb72-2"><a href="spatial-operations.html#cb72-2" aria-hidden="true" tabindex="-1"></a><span class="fu">st_length</span>(lnd_27700_border)</span></code></pre></div>
<pre><code>## Units: [m]
##  [1] 37553.153 58703.984 76164.278 58997.621 47439.044 63559.524 63887.056
##  [8] 33735.497 38334.168 50818.591 33856.826 34210.755 41169.745 47611.445
## [15] 45018.345 41064.695 33339.419 48674.312 39844.420 65245.555 32349.061
## [22] 38656.187 23940.326 20973.844 27304.280 26150.805 28683.830 20727.850
## [29] 25382.790 29025.112 34939.936 40695.572  9249.686</code></pre>
<p>The result shows the length of border of each boroughs in London. The unit is meters.</p>
<p>Last, <code>st_distance()</code> helps us to calculate the distance between pairs of geometric features. In transportation field, we often expect to calculate the distance of any two points, to roughly identify the radial distance of an OD pair, and construct the OD matrix. The elements of <code>st_distance()</code> is a bit complicated than the previous. Function <code>st_distance(x, y, by_element)</code> returns a dense numeric matrix of dimension length(x) by length(y) when parameter <code>by_element=F</code> (default). That is, if x consists of 5 points, and y consists of 4 points, then there are 5*4=20 results of distance, which is a complete matrix. If parameter <code>by_element=T</code> is set, then the distance is calculated by row, and the shorter one being recycled. And if there is only one data in the function, then it means to construct the complete distance matrix of the data. Here, we take the first five rows of data <code>nz_height</code> (data records the top 101 highest points in New Zealand) provided by <code>spData</code> for example.</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="spatial-operations.html#cb74-1" aria-hidden="true" tabindex="-1"></a>nz_height_5<span class="ot">=</span>nz_height[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>,]</span>
<span id="cb74-2"><a href="spatial-operations.html#cb74-2" aria-hidden="true" tabindex="-1"></a><span class="fu">st_distance</span>(nz_height_5)</span></code></pre></div>
<pre><code>## Units: [m]
##           [,1]      [,2]      [,3]      [,4]     [,5]
## [1,]      0.00  30627.85  31795.56  61597.89 205090.3
## [2,]  30627.85      0.00   1266.53  37715.86 180876.7
## [3,]  31795.56   1266.53      0.00  36606.75 179668.5
## [4,]  61597.89  37715.86  36606.75      0.00 144033.9
## [5,] 205090.28 180876.66 179668.50 144033.94      0.0</code></pre>
<p>With only one data in the function, the result shows the complete distance matrix of the 5 points. And now, a bit more complicated, let’s calculate the distance between the first 5 points to the centroid of its regions (polygons). In this case, we need to find out the region of each points located by using function <a href="spatial-operations.html#clipping"><code>st_intersection()</code></a>, and create a new variable called “nz_height_region.” However, doing intersection can only get the attribute of data <code>nz</code>, the geometry type remains “POINT.” Hence, we need to join the geometry data by using <code>left_join()</code> and use <a href="geographic-data.html#simple-feature-sf"><code>st_sf()</code></a> to re-make the simple feature data. The next step is to retrieve the centroid of each region, and create a new variable named “nz_height_region_centroid.” Last, we can calculate the distance of the points and the centroids of its region located in. And remember to add the parameter <code>by_element=T</code>, to ensure the distance is calculated by row, instead of a complete matrix. To sum up, the operation is tortuous, but review some of the basic operations mentioned in this chapter up to now.</p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="spatial-operations.html#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="co"># intersection to find out regions of each points located</span></span>
<span id="cb76-2"><a href="spatial-operations.html#cb76-2" aria-hidden="true" tabindex="-1"></a>nz_height_region<span class="ot">=</span><span class="fu">st_intersection</span>(nz_height_5, nz)</span>
<span id="cb76-3"><a href="spatial-operations.html#cb76-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-4"><a href="spatial-operations.html#cb76-4" aria-hidden="true" tabindex="-1"></a><span class="co"># left join to retrieve the geometries of polygon</span></span>
<span id="cb76-5"><a href="spatial-operations.html#cb76-5" aria-hidden="true" tabindex="-1"></a>nz_height_region<span class="ot">=</span><span class="fu">left_join</span>(<span class="fu">st_drop_geometry</span>(nz_height_region), nz)</span></code></pre></div>
<pre><code>## Joining, by = c(&quot;Name&quot;, &quot;Island&quot;, &quot;Land_area&quot;, &quot;Population&quot;, &quot;Median_income&quot;, &quot;Sex_ratio&quot;)</code></pre>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="spatial-operations.html#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="co"># the simple feature is converted to data frame, hence use st_sf() to retrieve the sf</span></span>
<span id="cb78-2"><a href="spatial-operations.html#cb78-2" aria-hidden="true" tabindex="-1"></a>nz_height_region<span class="ot">=</span><span class="fu">st_sf</span>(nz_height_region)</span>
<span id="cb78-3"><a href="spatial-operations.html#cb78-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-4"><a href="spatial-operations.html#cb78-4" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate the centroid of each region</span></span>
<span id="cb78-5"><a href="spatial-operations.html#cb78-5" aria-hidden="true" tabindex="-1"></a>nz_height_region_centroid<span class="ot">=</span><span class="fu">st_centroid</span>(nz_height_region)</span>
<span id="cb78-6"><a href="spatial-operations.html#cb78-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-7"><a href="spatial-operations.html#cb78-7" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate the distance of highest points and its region</span></span>
<span id="cb78-8"><a href="spatial-operations.html#cb78-8" aria-hidden="true" tabindex="-1"></a><span class="fu">st_distance</span>(nz_height_5, nz_height_region_centroid, <span class="at">by_element=</span>T)</span></code></pre></div>
<pre><code>## Units: [m]
## [1] 307518.0 280053.5 113454.4 116381.3 291094.6</code></pre>
<p>The geometric measurement is vital and basic in terms of doing spatial analysis. In this section, we can learn how to calculate the area, length and distance. The only issue we do not address is that the precision of calculation, if interested, please find other resources to get deeper understanding.</p>
</div>
<div id="nearest-analysis" class="section level2" number="5.13">
<h2><span class="header-section-number">5.13</span> Nearest Analysis</h2>
<p>In practical issue, we often want to know the nearest point of the feature, for instance, the nearest MRT station of the school. One method is to construct the complete distance matrix, and filter the nearest one by using function <code>st_distance()</code>. But obviously, it sounds very time-consuming. Package <code>sf</code> provided a function called <code>st_nearest_feature()</code> to get the index of the nearest geometry. Let’s take Youbike and MRT Station in Taipei for example, and supposed we want to know the nearest MRT station of each YouBike station. <font color="red"><em><em>Data needed has been downloaded previously. You placed the file in the same directory as the R script file.</em></em> Click <a href="https://drive.google.com/uc?export=download&amp;id=1TSavur6YcaJO5DCCb5Hsb0HICdwZpeXi"><strong>here</strong></a> to re-download the file if it is lost.</font></p>
<p>In function <code>st_nearest_feature(X, Y)</code>, the result shows that for each geometry in X, the index of the nearest geometry in set Y. In our case, we want to know the nearest MRT station of YouBike station, and hence, we should place YouBike data in the first parameter (X), while the MRT data should be placed in the second parameter. The code and result are shown below.</p>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="spatial-operations.html#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="co"># import the shapefile</span></span>
<span id="cb80-2"><a href="spatial-operations.html#cb80-2" aria-hidden="true" tabindex="-1"></a>taipei_mrt_station<span class="ot">=</span><span class="fu">read_sf</span>(<span class="st">&quot;./data/taipei_mrt/taipei_mrt_station.shp&quot;</span>)</span>
<span id="cb80-3"><a href="spatial-operations.html#cb80-3" aria-hidden="true" tabindex="-1"></a>taipei_youbike<span class="ot">=</span><span class="fu">read_sf</span>(<span class="st">&quot;./data/taipei_youbike/taipei_youbike.shp&quot;</span>)</span>
<span id="cb80-4"><a href="spatial-operations.html#cb80-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-5"><a href="spatial-operations.html#cb80-5" aria-hidden="true" tabindex="-1"></a><span class="co"># find the nearest feature</span></span>
<span id="cb80-6"><a href="spatial-operations.html#cb80-6" aria-hidden="true" tabindex="-1"></a>near_mrt<span class="ot">=</span><span class="fu">st_nearest_feature</span>(taipei_youbike, taipei_mrt_station)</span>
<span id="cb80-7"><a href="spatial-operations.html#cb80-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-8"><a href="spatial-operations.html#cb80-8" aria-hidden="true" tabindex="-1"></a><span class="co"># st_nearest_feature gives the index of the MRT data</span></span>
<span id="cb80-9"><a href="spatial-operations.html#cb80-9" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(near_mrt)</span></code></pre></div>
<pre><code>## [1] 116 115 116  26  25  26</code></pre>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="spatial-operations.html#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="co"># combine the data</span></span>
<span id="cb82-2"><a href="spatial-operations.html#cb82-2" aria-hidden="true" tabindex="-1"></a>near_mrt_result<span class="ot">=</span><span class="fu">data.frame</span>(<span class="at">YouBike=</span>taipei_youbike<span class="sc">$</span>StatnNm,</span>
<span id="cb82-3"><a href="spatial-operations.html#cb82-3" aria-hidden="true" tabindex="-1"></a>                           <span class="at">MRT=</span>taipei_mrt_station[near_mrt,]<span class="sc">$</span>Zh_tw)</span>
<span id="cb82-4"><a href="spatial-operations.html#cb82-4" aria-hidden="true" tabindex="-1"></a><span class="co"># near_mrt_result</span></span></code></pre></div>
<div id="htmlwidget-724296c2fd6498b9c481" style="width:100%;height:auto;" class="datatables html-widget"></div>
<script type="application/json" data-for="htmlwidget-724296c2fd6498b9c481">{"x":{"filter":"none","data":[["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36","37","38","39","40","41","42","43","44","45","46","47","48","49","50","51","52","53","54","55","56","57","58","59","60","61","62","63","64","65","66","67","68","69","70","71","72","73","74","75","76","77","78","79","80","81","82","83","84","85","86","87","88","89","90","91","92","93","94","95","96","97","98","99","100","101","102","103","104","105","106","107","108","109","110","111","112","113","114","115","116","117","118","119","120","121","122","123","124","125","126","127","128","129","130","131","132","133","134","135","136","137","138","139","140","141","142","143","144","145","146","147","148","149","150","151","152","153","154","155","156","157","158","159","160","161","162","163","164","165","166","167","168","169","170","171","172","173","174","175","176","177","178","179","180","181","182","183","184","185","186","187","188","189","190","191","192","193","194","195","196","197","198","199","200","201","202","203","204","205","206","207","208","209","210","211","212","213","214","215","216","217","218","219","220","221","222","223","224","225","226","227","228","229","230","231","232","233","234","235","236","237","238","239","240","241","242","243","244","245","246","247","248","249","250","251","252","253","254","255","256","257","258","259","260","261","262","263","264","265","266","267","268","269","270","271","272","273","274","275","276","277","278","279","280","281","282","283","284","285","286","287","288","289","290","291","292","293","294","295","296","297","298","299","300","301","302","303","304","305","306","307","308","309","310","311","312","313","314","315","316","317","318","319","320","321","322","323","324","325","326","327","328","329","330","331","332","333","334","335","336","337","338","339","340","341","342","343","344","345","346","347","348","349","350","351","352","353","354","355","356","357","358","359","360","361","362","363","364","365","366","367","368","369","370","371","372","373","374","375","376","377","378","379","380","381","382","383","384","385","386","387","388","389","390","391","392","393","394","395","396","397","398","399","400","401","402","403","404","405","406","407","408","409","410","411","412","413","414","415","416","417","418","419","420","421","422","423","424","425","426","427","428","429","430","431","432","433","434","435","436","437","438","439","440","441","442","443","444","445","446","447","448","449","450","451","452","453","454","455","456","457","458","459","460","461","462","463","464","465","466","467","468","469","470","471","472","473","474","475","476","477","478","479","480","481","482","483","484","485","486","487","488","489","490","491","492","493","494","495","496","497","498","499","500","501","502","503","504","505","506","507","508","509","510","511","512","513","514","515","516","517","518","519","520","521","522","523","524","525","526","527","528","529","530","531","532","533","534","535","536","537","538","539","540","541","542","543","544","545","546","547","548","549","550","551","552","553","554","555","556","557","558","559","560","561","562","563","564","565","566","567","568","569","570","571","572","573","574","575","576","577","578","579","580","581","582","583","584","585","586","587","588","589","590","591","592","593","594","595","596","597","598","599","600","601","602","603","604","605","606","607","608","609","610","611","612","613","614","615","616","617","618","619","620","621","622","623","624","625","626","627","628","629","630","631","632","633","634","635","636","637","638","639","640","641","642","643","644","645","646","647","648","649","650","651","652","653","654","655","656","657","658","659","660","661","662","663","664","665","666","667","668","669","670","671","672","673","674","675","676","677","678","679","680","681","682","683","684","685","686","687","688","689","690","691","692","693","694","695","696","697","698","699","700","701","702","703","704","705","706","707","708","709","710","711","712","713","714","715","716","717","718","719","720","721","722","723","724","725","726","727","728","729","730","731","732","733","734","735","736","737","738","739","740","741","742","743","744","745","746","747","748","749","750","751","752","753","754","755","756","757","758","759","760","761","762","763","764","765","766","767","768","769","770","771","772","773","774","775","776","777","778","779","780","781","782","783","784","785","786","787","788","789","790","791","792","793","794","795","796","797","798","799","800","801","802","803","804","805","806","807","808","809","810","811","812","813","814","815","816","817","818","819","820","821","822","823","824","825","826","827","828","829","830","831","832","833","834","835","836","837","838","839","840","841","842","843","844","845","846","847","848","849","850","851","852","853","854","855","856","857","858","859","860","861","862","863","864","865","866","867","868","869","870","871","872","873","874","875","876","877","878","879","880","881","882","883","884","885","886","887","888","889","890","891","892","893","894","895","896","897","898","899","900","901","902","903","904","905","906","907","908","909","910","911","912","913"],["YouBike1.0_捷運市政府站(3號出口)","YouBike1.0_捷運國父紀念館站(2號出口)","YouBike1.0_台北市政府","YouBike1.0_市民廣場","YouBike1.0_興雅國中","YouBike1.0_臺北南山廣場","YouBike1.0_信義廣場(台北101)","YouBike1.0_世貿三館","YouBike1.0_松德站","YouBike1.0_台北市災害應變中心","YouBike1.0_三張犁","YouBike1.0_臺北醫學大學","YouBike1.0_福德公園","YouBike1.0_榮星花園","YouBike1.0_松山家商","YouBike1.0_民生光復路口","YouBike1.0_臺北市藝文推廣處","YouBike1.0_象山公園","YouBike1.0_民生敦化路口","YouBike1.0_松山車站","YouBike1.0_東新國小","YouBike1.0_信義建國路口","YouBike1.0_永吉松信路口","YouBike1.0_捷運昆陽站(1號出口)","YouBike1.0_捷運南港展覽館站(5號出口)","YouBike1.0_五常公園","YouBike1.0_金山愛國路口","YouBike1.0_基隆長興路口","YouBike1.0_辛亥新生路口","YouBike1.0_捷運六張犁站","YouBike1.0_中崙高中","YouBike1.0_捷運行天宮站(1號出口)","YouBike1.0_捷運行天宮站(3號出口)","YouBike1.0_臺大資訊大樓","YouBike1.0_捷運東門站(4號出口)","YouBike1.0_臺灣師範大學(圖書館)","YouBike1.0_南港世貿公園","YouBike1.0_玉成公園","YouBike1.0_中研公園","YouBike1.0_捷運後山埤站(1號出口)","YouBike1.0_凌雲市場","YouBike1.0_捷運南港軟體園區站(2號出口)","YouBike1.0_捷運公館站(2號出口)","YouBike1.0_南港國小","YouBike1.0_捷運忠孝新生站(4號出口)","YouBike1.0_南港車站(忠孝東路)","YouBike1.0_龍門廣場","YouBike1.0_民權運動公園","YouBike1.0_建國農安街口","YouBike1.0_建國長春路口","YouBike1.0_八德市場","YouBike1.0_臺北市立圖書館(總館)","YouBike1.0_臺北田徑場","YouBike1.0_仁愛林森路口","YouBike1.0_新生和平路口","YouBike1.0_捷運善導寺站(1號出口)","YouBike1.0_林森公園","YouBike1.0_中山行政中心","YouBike1.0_台灣科技大學","YouBike1.0_南昌公園","YouBike1.0_仁愛醫院","YouBike1.0_國家圖書館","YouBike1.0_青年公園3號出口","YouBike1.0_師範大學公館校區","YouBike1.0_捷運臺大醫院(4號出口)","YouBike1.0_國興青年路口","YouBike1.0_興豐公園","YouBike1.0_捷運台北101/世貿站","YouBike1.0_捷運信義安和站(4號出口)","YouBike1.0_新生長安路口","YouBike1.0_酒泉延平路口","YouBike1.0_信義連雲街口","YouBike1.0_基隆光復路口","YouBike1.0_新生長春路口","YouBike1.0_民生活動中心","YouBike1.0_捷運圓山站(2號出口)","YouBike1.0_捷運民權西路站(3號出口)","YouBike1.0_華江高中","YouBike1.0_捷運台電大樓站(2號出口)","YouBike1.0_捷運西門站(3號出口)","YouBike1.0_捷運大安森林公園站","YouBike1.0_復華花園新城","YouBike1.0_信義敦化路口","YouBike1.0_民權復興路口","YouBike1.0_捷運大安站","YouBike1.0_捷運象山站","YouBike1.0_和平重慶路口","YouBike1.0_老松國小","YouBike1.0_市立美術館","YouBike1.0_開封西寧路口","YouBike1.0_吳興公車總站","YouBike1.0_捷運景美站","YouBike1.0_東園國小","YouBike1.0_三民公園","YouBike1.0_捷運劍潭站(2號出口)","YouBike1.0_羅斯福景隆街口","YouBike1.0_捷運雙連站(2號出口)","YouBike1.0_金山市民路口","YouBike1.0_華山文創園區","YouBike1.0_臺北市客家文化主題公園","YouBike1.0_萬華車站","YouBike1.0_台北花木批發市場","YouBike1.0_峨嵋停車場","YouBike1.0_西園艋舺路口","YouBike1.0_捷運小南門站(1號出口)","YouBike1.0_臺北孔廟","YouBike1.0_林安泰古厝","YouBike1.0_文湖國小","YouBike1.0_捷運忠孝復興站(2號出口)","YouBike1.0_捷運新北投站","YouBike1.0_仁愛逸仙路口","YouBike1.0_蘭雅公園","YouBike1.0_臺北轉運站","YouBike1.0_福林公園","YouBike1.0_捷運北投站","YouBike1.0_大業大同街口","YouBike1.0_捷運劍南路站(2號出口)","YouBike1.0_捷運龍山寺站(1號出口)","YouBike1.0_龍江南京路口","YouBike1.0_捷運港墘站(2號出口)","YouBike1.0_天母運動公園","YouBike1.0_振華公園","YouBike1.0_華西公園","YouBike1.0_敦化基隆路口","YouBike1.0_東湖國中","YouBike1.0_成功國宅","YouBike1.0_捷運文德站(2號出口)","YouBike1.0_羅斯福寧波東街口","YouBike1.0_洲子二號公園","YouBike1.0_羅斯福新生南路口","YouBike1.0_蘭興公園","YouBike1.0_捷運芝山站(2號出口)","YouBike1.0_捷運石牌站(2號出口)","YouBike1.0_國立臺北護理健康大學","YouBike1.0_國防大學","YouBike1.0_捷運永春站(2號出口)","YouBike1.0_永樂市場","YouBike1.0_捷運大橋頭站(2號出口)","YouBike1.0_文山行政中心","YouBike1.0_捷運木柵站","YouBike1.0_捷運動物園站(2號出口)","YouBike1.0_國立政治大學","YouBike1.0_樹德公園","YouBike1.0_捷運士林站(2號出口)","YouBike1.0_士林運動中心","YouBike1.0_捷運明德站","YouBike1.0_北投運動中心","YouBike1.0_松德公園","YouBike1.0_考試院","YouBike1.0_百齡國小","YouBike1.0_蔣渭水紀念公園","YouBike1.0_中正基河路口","YouBike1.0_瑞光港墘路口","YouBike1.0_東湖國小","YouBike1.0_麗山國小","YouBike1.0_捷運東湖站","YouBike1.0_捷運西湖站(1號出口)","YouBike1.0_大豐公園","YouBike1.0_捷運中山國小站(4號出口)","YouBike1.0_捷運麟光站","YouBike1.0_捷運奇岩站","YouBike1.0_捷運唭哩岸站(2號出口)","YouBike1.0_臺北市立景美女中","YouBike1.0_臺北市立天文館","YouBike1.0_河堤國小","YouBike1.0_植物園","YouBike1.0_新東公園","YouBike1.0_文山運動中心","YouBike1.0_捷運南京三民站(1號出口)","YouBike1.0_捷運松江南京站(7號出口)","YouBike1.0_捷運小巨蛋站(5號出口)","YouBike1.0_捷運南京復興站(5號出口)","YouBike1.0_興安華城","YouBike1.0_葫蘆國小","YouBike1.0_延平國宅","YouBike1.0_南港公園","YouBike1.0_福華商場","YouBike1.0_建國和平路口","YouBike1.0_捷運古亭站(2號出口)","YouBike1.0_圓環站","YouBike1.0_劍潭社區","YouBike1.0_瑠公公園","YouBike1.0_臺北市立大學","YouBike1.0_仁愛延吉街口","YouBike1.0_社子國小","YouBike1.0_金瑞公園(金龍路)","YouBike1.0_捷運大直站(3號出口)","YouBike1.0_捷運大湖公園站(2號出口)","YouBike1.0_捷運葫洲站(1號出口)","YouBike1.0_舊莊區民活動中心","YouBike1.0_市民林森路口","YouBike1.0_信義杭州路口(中華電信總公司)","YouBike1.0_新湖國小","YouBike1.0_饒河夜市(八德路側)","YouBike1.0_東陽公園","YouBike1.0_捷運關渡站","YouBike1.0_古亭國中","YouBike1.0_臺北市立大學(天母校區)","YouBike1.0_木柵光輝路口","YouBike1.0_捷運辛亥站","YouBike1.0_福安國中","YouBike1.0_龍山國小","YouBike1.0_捷運復興崗站","YouBike1.0_樂群二敬業四路口","YouBike1.0_星雲金湖街口","YouBike1.0_北安大直街口","YouBike1.0_蘭雅國小","YouBike1.0_基河一期國宅","YouBike1.0_捷運北門站(3號出口)","YouBike1.0_培英公園","YouBike1.0_臺北花市","YouBike1.0_松山高中","YouBike1.0_大理高中","YouBike1.0_大稻埕公園","YouBike1.0_泰和公園","YouBike1.0_撫順公園","YouBike1.0_清江國小","YouBike1.0_社正公園","YouBike1.0_臥龍樂業街口","YouBike1.0_向陽南港路口","YouBike1.0_麗山高中","YouBike1.0_捷運萬芳社區站","YouBike1.0_市民太原路口","YouBike1.0_湖光國宅","YouBike1.0_內政部營建署","YouBike1.0_中山天母路口","YouBike1.0_捷運忠義站","YouBike1.0_永欣綠地","YouBike1.0_市民東興路口","YouBike1.0_關渡自然公園","YouBike1.0_文山第二行政中心","YouBike1.0_瑞湖陽光街口","YouBike1.0_新明路262巷口","YouBike1.0_南京建國路口","YouBike1.0_林口公園","YouBike1.0_關渡宮","YouBike1.0_社子公園","YouBike1.0_復興市民路口","YouBike1.0_捷運中山國中站","YouBike1.0_國立故宮博物院","YouBike1.0_木柵公園","YouBike1.0_喬治工商","YouBike1.0_中華桂林路口","YouBike1.0_忠孝東路三段217巷口","YouBike1.0_華齡公園","YouBike1.0_大安運動中心","YouBike1.0_芝山抽水站","YouBike1.0_立功立德路口","YouBike1.0_光復南路22巷口","YouBike1.0_中山中正路口","YouBike1.0_錦德公園","YouBike1.0_聯合醫院中興院區","YouBike1.0_南京遼寧街口","YouBike1.0_民權瑞光路口","YouBike1.0_健康新城","YouBike1.0_永安藝文館-表演36房","YouBike1.0_至善臨溪路口","YouBike1.0_秀山區民活動中心","YouBike1.0_中央北路四段30巷口","YouBike1.0_洲子一號公園","YouBike1.0_八德中坡路口","YouBike1.0_南港高工","YouBike1.0_三軍總醫院","YouBike1.0_雨農國小","YouBike1.0_伊通長安路口","YouBike1.0_忠順區民活動中心","YouBike1.0_芝山國小","YouBike1.0_扶輪親恩公園","YouBike1.0_西本願寺廣場","YouBike1.0_三興公園","YouBike1.0_中山堂","YouBike1.0_明美公園","YouBike1.0_南港車站(興華路)","YouBike1.0_士林新天地","YouBike1.0_松江公園","YouBike1.0_富台公園","YouBike1.0_中央北路四段540巷口","YouBike1.0_華聲公園","YouBike1.0_螢橋國小","YouBike1.0_德明財經科技大學","YouBike1.0_第二果菜批發市場","YouBike1.0_濟南紹興路口","YouBike1.0_牯嶺公園","YouBike1.0_新生公園","YouBike1.0_捷運松山站(3號出口)","YouBike1.0_合心廣場","YouBike1.0_自來水園區","YouBike1.0_朱崙商場","YouBike1.0_敦親公園","YouBike1.0_萬和二號公園","YouBike1.0_長沙公園","YouBike1.0_太原五原路口","YouBike1.0_萬華國中","YouBike1.0_信義基隆路口","YouBike1.0_林森長春路口","YouBike1.0_敦北公園","YouBike1.0_安泰街83巷","YouBike1.0_金華公園","YouBike1.0_碧山公園","YouBike1.0_捷運古亭站(6號出口)","YouBike1.0_仁愛安和路口","YouBike1.0_西松高中","YouBike1.0_三軍總醫院(松山分院)","YouBike1.0_國立臺北大學(臺北校區)","YouBike1.0_捷運忠孝新生站(2號出口)","YouBike1.0_捷運信義安和站(1號出口)","YouBike1.0_光華商場","YouBike1.0_敦化長春路口","YouBike1.0_捷運萬隆站(1號出口)","YouBike1.0_民有一號公園","YouBike1.0_雙園國中","YouBike1.0_成功金龍路口","YouBike1.0_民族林森路口","YouBike1.0_捷運南京三民站(3號出口)","YouBike1.0_莒光大埔街口","YouBike1.0_永盛公園(民生東路一段23巷)","YouBike1.0_新興公園","YouBike1.0_市立圖書館葫蘆堵分館","YouBike1.0_南京東路六段368巷","YouBike1.0_基隆路一段101巷口","YouBike1.0_重慶南海路口","YouBike1.0_一江公園","YouBike1.0_樂群二明水路口","YouBike1.0_迪化休閒運動公園","YouBike1.0_民族玉門街口","YouBike1.0_捷運中山站(2號出口)","YouBike1.0_復盛公園","YouBike1.0_敦化南路二段103巷口","YouBike1.0_景文中學","YouBike1.0_承德路三段8巷口","YouBike1.0_彩虹橋","YouBike1.0_成德國中","YouBike1.0_重慶國中","YouBike1.0_南京光復路口","YouBike1.0_捷運芝山站(1號出口)","YouBike1.0_文林建民路口","YouBike1.0_忠孝東路六段185巷口","YouBike1.0_捷運忠孝復興站(5號出口)","YouBike1.0_中正運動中心","YouBike1.0_陽明高中","YouBike1.0_博愛寶慶路口","YouBike1.0_民生立體停車場","YouBike1.0_重慶酒泉街口","YouBike1.0_復興南路二段128巷口","YouBike1.0_中山青島路口","YouBike1.0_民權迪化街口","YouBike1.0_紀州庵","YouBike1.0_建國濟南路口","YouBike1.0_福山公園","YouBike1.0_臺北市網球中心","YouBike1.0_松友公園","YouBike1.0_新明成功路口","YouBike1.0_健安新城","YouBike1.0_民權建國路口","YouBike1.0_振興醫院","YouBike1.0_和平金山路口","YouBike1.0_復興南路一段340巷口","YouBike1.0_嘉興公園","YouBike1.0_陽明大學","YouBike1.0_碧湖公園","YouBike1.0_豐年公園","YouBike1.0_臺灣戲曲中心","YouBike1.0_世新大學","YouBike1.0_新和國小","YouBike1.0_南門國中","YouBike1.0_重慶民族路口","YouBike1.0_中崙福成宮","YouBike1.0_麗湖國小","YouBike1.0_銘傳大學","YouBike1.0_民生建國路口","YouBike1.0_南港路二段178巷口","YouBike1.0_陽光街321巷口","YouBike1.0_春光公園","YouBike1.0_塔悠疏散門","YouBike1.0_民權東路六段15巷","YouBike1.0_聯合醫院和平院區","YouBike1.0_一壽橋","YouBike1.0_松基公園","YouBike1.0_和興路26巷口","YouBike1.0_錦州吉林路口","YouBike1.0_吳興街260巷","YouBike1.0_景華街128巷口","YouBike1.0_福德國小","YouBike1.0_稻香重三路口","YouBike1.0_景仁公園","YouBike1.0_南京東興路口","YouBike1.0_內溝溪生態展示館","YouBike1.0_松德虎林街口","YouBike1.0_安強公園","YouBike1.0_新東街51巷口","YouBike1.0_劍潭海外青年活動中心","YouBike1.0_聯合醫院陽明院區","YouBike1.0_和平龍泉街口","YouBike1.0_和平敦化路口","YouBike1.0_南京新生路口","YouBike1.0_下灣公園","YouBike1.0_捷運內湖站(1號出口)","YouBike1.0_民族延平路口","YouBike1.0_捷運科技大樓站(台北教育大學)","YouBike2.0_捷運科技大樓站","YouBike2.0_復興南路二段273號前","YouBike2.0_國北教大實小東側門","YouBike2.0_和平公園東側","YouBike2.0_辛亥復興路口西北側","YouBike2.0_復興南路二段280號前","YouBike2.0_復興南路二段340巷口","YouBike2.0_新生南路三段52號前","YouBike2.0_新生南路三段66號前","YouBike2.0_新生南路三段82號前","YouBike2.0_羅斯福路三段333巷9號旁","YouBike2.0_辛亥路一段30號前","YouBike2.0_和平復興路口西北側","YouBike2.0_羅斯福路三段311號前","YouBike2.0_大安運動中心停車場","YouBike2.0_羅斯福路三段245號前","YouBike2.0_羅斯福路三段269巷5號前","YouBike2.0_溫州公園","YouBike2.0_和平臥龍街口","YouBike2.0_溫州停車場","YouBike2.0_銘傳國小側門","YouBike2.0_捷運公館站(2號出口)","YouBike2.0_第二學生活動中心","YouBike2.0_臺灣科技大學正門","YouBike2.0_臺灣科技大學側門","YouBike2.0_公館公園","YouBike2.0_臺灣科技大學後門","YouBike2.0_臺大醫學院附設癌醫中心","YouBike2.0_臺大環研大樓","YouBike2.0_臺大永齡生醫工程館","YouBike2.0_臺大男七舍前","YouBike2.0_臺大男一舍前","YouBike2.0_臺大男六舍前","YouBike2.0_臺大動物醫院前","YouBike2.0_臺大土木研究大樓前","YouBike2.0_臺大萬才館前","YouBike2.0_臺大國青大樓宿舍前","YouBike2.0_臺大社科院圖書館前","YouBike2.0_臺大法人語言訓練中心前","YouBike2.0_臺大綜合體育館停車場前","YouBike2.0_辛亥新生路口東南側","YouBike2.0_基隆長興路口東側","YouBike2.0_國北教大側門南側","YouBike2.0_和平實小東北側","YouBike2.0_大安區健康服務中心","YouBike2.0_辛亥泰順街口","YouBike2.0_芳和國中","YouBike2.0_辛亥基隆路口","YouBike2.0_臥龍樂業街口","YouBike2.0_臥龍公園","YouBike2.0_嘉興公園","YouBike2.0_捷運麟光站(2號出口)","YouBike2.0_捷運六張犁站","YouBike2.0_喬治工商","YouBike2.0_法治公園","YouBike2.0_捷運臺電大樓站(2號出口)","YouBike2.0_和平金山路口","YouBike2.0_和平龍泉街口","YouBike2.0_和平泰順街口","YouBike2.0_臺灣師範大學(圖書館)","YouBike2.0_捷運古亭站(6號出口)","YouBike2.0_捷運古亭站(5號出口)","YouBike2.0_臺北市立圖書館(總館)","YouBike2.0_新生和平路口東北側","YouBike2.0_建國和平路口西北側","YouBike2.0_金華公園","YouBike2.0_捷運東門站(3號出口)","YouBike2.0_金甌女中","YouBike2.0_金杭公園","YouBike2.0_愛國金山路口","YouBike2.0_敦化南路二段293巷口南側","YouBike2.0_敦化基隆路口","YouBike2.0_安和路二段181巷口","YouBike2.0_臨江街夜市(通化街101巷口)","YouBike2.0_臨江街夜市(基隆路)","YouBike2.0_台北科技大學億光大樓","YouBike2.0_新生南路一段119巷口","YouBike2.0_幸安國小(仁愛路)","YouBike2.0_民榮公園","YouBike2.0_復興南路1段340巷口","YouBike2.0_建國濟南路口","YouBike2.0_捷運忠孝復興站(2號出口)","YouBike2.0_捷運大安站(4號出口)","YouBike2.0_捷運大安站(2號出口)","YouBike2.0_信義大安路口(信維大樓)","YouBike2.0_龍門廣場","YouBike2.0_信義敦化路口","YouBike2.0_仁愛國中","YouBike2.0_捷運信義安和站(2號出口)","YouBike2.0_八德市場","YouBike2.0_昌隆公園","YouBike2.0_捷運大安森林公園站(2號出口)","YouBike2.0_信義延吉街口","YouBike2.0_光信公園(光復南路456巷)","YouBike2.0_僑安地下停車場(2號出口)東南側","YouBike2.0_建國南路一段279巷口","YouBike2.0_捷運忠孝新生站(6號出口)","YouBike2.0_大安高工","YouBike2.0_捷運忠孝新生站(3號出口)","YouBike2.0_瑠公公園","YouBike2.0_敦化市民路口","YouBike2.0_延平國宅","YouBike2.0_劍潭抽水站","YouBike2.0_通河東街大南路口","YouBike2.0_福港街停車場","YouBike2.0_百齡國小","YouBike2.0_雨聲街165巷口","YouBike2.0_天和公園","YouBike2.0_中山天母路口","YouBike2.0_天母運動公園","YouBike2.0_臺北市立大學(天母校區)","YouBike2.0_忠誠路二段53巷","YouBike2.0_天母國中","YouBike2.0_天母棒球場","YouBike2.0_天母北天玉街口","YouBike2.0_蘭興公園","YouBike2.0_明勝公園","YouBike2.0_劍潭海外青年活動中心","YouBike2.0_忠誠路一段173巷口","YouBike2.0_雨農國小","YouBike2.0_忠誠公園","YouBike2.0_芝山抽水站","YouBike2.0_至誠路一段305巷口","YouBike2.0_華齡公園","YouBike2.0_前港公園(福德宮)","YouBike2.0_華齡街185巷口","YouBike2.0_前港公園(前港街)","YouBike2.0_百齡高中","YouBike2.0_捷運芝山站(2號出口)","YouBike2.0_臺灣戲曲中心","YouBike2.0_捷運劍潭站(2號出口)","YouBike2.0_劍潭基河路口","YouBike2.0_志成公園","YouBike2.0_福林國小","YouBike2.0_中山中正路口","YouBike2.0_士林運動中心","YouBike2.0_陽明高中","YouBike2.0_兒童新樂園","YouBike2.0_臺北市立天文館","YouBike2.0_華聲公園","YouBike2.0_福林公園","YouBike2.0_捷運士林站(2號出口)","YouBike2.0_銘傳大學","YouBike2.0_士林高商","YouBike2.0_蘭雅公園","YouBike2.0_聯合醫院陽明院區","YouBike2.0_捷運芝山站(1號出口)","YouBike2.0_至誠公園","YouBike2.0_原住民文化主題公園","YouBike2.0_通河東街2段10巷口","YouBike2.0_梅林新村","YouBike2.0_延平北中正路口","YouBike2.0_重慶北路四段190巷口","YouBike2.0_重慶北葫東街口","YouBike2.0_葫蘆國小","YouBike2.0_士林3號廣場","YouBike2.0_社正公園","YouBike2.0_社子國小","YouBike2.0_社中街384巷口","YouBike2.0_忠誠路一段138號","YouBike2.0_社子公園","YouBike2.0_國立故宮博物院","YouBike2.0_泰北高中","YouBike2.0_後港公園","YouBike2.0_重慶北路四段117號","YouBike2.0_社子島島頭公園","YouBike2.0_延平北路八段133巷口","YouBike2.0_坤天亭","YouBike2.0_社子島濕地解說小築","YouBike2.0_福安國中","YouBike2.0_福安消防分隊","YouBike2.0_聖山綠地","YouBike2.0_台北花木批發市場","YouBike2.0_捷運萬隆站(4號出口)","YouBike2.0_捷運萬隆站(1號出口)","YouBike2.0_萬和二號公園","YouBike2.0_捷運萬隆站(2號出口)","YouBike2.0_景仁公園","YouBike2.0_捷運景美站(2號出口)","YouBike2.0_羅斯福景隆街口","YouBike2.0_景福街/羅斯福路6段142巷口","YouBike2.0_興福國中","YouBike2.0_興隆路2段203巷","YouBike2.0_景美運動公園","YouBike2.0_師範大學公館校區","YouBike2.0_仙跡岩登山口(景興路)","YouBike2.0_捷運木柵站","YouBike2.0_捷運萬芳社區站","YouBike2.0_捷運辛亥站","YouBike2.0_興豐公園","YouBike2.0_世新大學","YouBike2.0_臺北市立景美女中","YouBike2.0_永安藝文館-表演36房","YouBike2.0_忠順區民活動中心","YouBike2.0_景文中學","YouBike2.0_臺北自來水事業處","YouBike2.0_汀州思源街口東南側","YouBike2.0_捷運公館站(1號出口)","YouBike2.0_捷運公館站(4號出口)","YouBike2.0_捷運古亭站(9號出口)","YouBike2.0_捷運古亭站(2號出口)","YouBike2.0_捷運臺電大樓站(1號出口)","YouBike2.0_客家文化主題公園","YouBike2.0_河堤國小","YouBike2.0_紀州庵","YouBike2.0_捷運臺電大樓站(5號出口)","YouBike2.0_捷運臺電大樓站(4號出口)","YouBike2.0_羅斯福三段金門街口","YouBike2.0_牯嶺公園","YouBike2.0_捷運古亭站(8號出口)","YouBike2.0_捷運古亭站(7號出口)","YouBike2.0_南昌公園","YouBike2.0_和平重慶路口","YouBike2.0_孫立人將軍官邸","YouBike2.0_羅斯福路二段6巷口","YouBike2.0_金華杭州南路口","YouBike2.0_捷運中正紀念堂站(3號出口)","YouBike2.0_捷運中正紀念堂站(4號出口)","YouBike2.0_重慶南海路口西南側","YouBike2.0_螢橋國小","YouBike2.0_古亭智慧圖書館","YouBike2.0_永昌公園","YouBike2.0_中華路二段409巷口","YouBike2.0_南機場夜市(中華路二段)","YouBike2.0_南海和平路口西南側","YouBike2.0_莒光和平路口","YouBike2.0_水源路11-1號旁","YouBike2.0_南門國中","YouBike2.0_捷運小南門站(2號出口)","YouBike2.0_介壽公園","YouBike2.0_中華貴陽街口","YouBike2.0_華山文創園區","YouBike2.0_捷運善導寺站(1號出口)","YouBike2.0_濟南紹興路口","YouBike2.0_林森仁愛路口","YouBike2.0_中正運動中心","YouBike2.0_信義杭州路口","YouBike2.0_捷運善導寺站(3號出口)","YouBike2.0_捷運小南門站(1號出口)","YouBike2.0_延平南路133巷口","YouBike2.0_捷運西門站(2號出口)","YouBike2.0_寶慶博愛路口","YouBike2.0_法務部","YouBike2.0_臺北市立大學(博愛校區)","YouBike2.0_國家圖書館","YouBike2.0_市民金山路口","YouBike2.0_中山堂","YouBike2.0_中華漢口街口","YouBike2.0_中華路一段21巷口","YouBike2.0_捷運臺大醫院站(4號出口)","YouBike2.0_寶藏巖觀音亭","YouBike2.0_通北街65巷口","YouBike2.0_圓山風景區","YouBike2.0_樂群二堤頂大道口","YouBike2.0_劍潭社區","YouBike2.0_培英公園","YouBike2.0_樂群二明水路口","YouBike2.0_北安大直街口","YouBike2.0_捷運劍南路站(2號出口)","YouBike2.0_樂群二敬業三路口","YouBike2.0_樂群二敬業四路口","YouBike2.0_捷運大直站(3號出口)","YouBike2.0_文湖街21巷118弄口","YouBike2.0_北勢湖環保公園","YouBike2.0_洲子一號公園","YouBike2.0_西康公園","YouBike2.0_文湖國小","YouBike2.0_文湖街81巷10號西側","YouBike2.0_德明財經科技大學","YouBike2.0_麗山國小","YouBike2.0_麗山高中","YouBike2.0_港華五號公園","YouBike2.0_大湖國小","YouBike2.0_安湖三號公園","YouBike2.0_東湖路113巷95弄","YouBike2.0_瑞光計程車服務站","YouBike2.0_文德三號公園(江南街71巷16弄)","YouBike2.0_捷運大湖公園站(2號出口)","YouBike2.0_康寧星雲街口","YouBike2.0_星雲街47號","YouBike2.0_捷運西湖站(1號出口)","YouBike2.0_捷運西湖站(2號出口)","YouBike2.0_洲子二號公園","YouBike2.0_港都公園","YouBike2.0_環山路二段26巷口","YouBike2.0_成功金龍路口","YouBike2.0_碧山公園","YouBike2.0_金瑞公園","YouBike2.0_捷運文德站(2號出口)","YouBike2.0_陽光公園","YouBike2.0_文德二號公園(南側)","YouBike2.0_文德二號公園(北側)","YouBike2.0_瑞陽公園","YouBike2.0_湖光國宅","YouBike2.0_潭美街213號","YouBike2.0_南京東路六段180號","YouBike2.0_潭美國小(南京舊宗路口)","YouBike2.0_新明路343號","YouBike2.0_週美里活動廣場","YouBike2.0_樂康公園","YouBike2.0_安康路34巷24弄","YouBike2.0_明美公園","YouBike2.0_南京東路六段368巷","YouBike2.0_新明成功路口","YouBike2.0_民權瑞光路口","YouBike2.0_瑞光公共住宅(瑞光路)","YouBike2.0_民權東路六段15巷","YouBike2.0_扶輪親恩公園","YouBike2.0_新湖三民善街口","YouBike2.0_內湖119號綠地","YouBike2.0_行善公園","YouBike2.0_三軍總醫院","YouBike2.0_臺北市網球中心","YouBike2.0_捷運葫洲站(1號出口)","YouBike2.0_麗湖國小","YouBike2.0_金湖路347巷125弄口","YouBike2.0_碧湖公園","YouBike2.0_碧湖公園(內湖路二段103巷)","YouBike2.0_貿七社區","YouBike2.0_內湖區農會","YouBike2.0_康寧金湖路口","YouBike2.0_康寧路一段156巷20弄口","YouBike2.0_安康公園","YouBike2.0_安泰街83巷","YouBike2.0_內溝溪生態展示館","YouBike2.0_捷運港墘站(2號出口)","YouBike2.0_承德路七段304巷口","YouBike2.0_洲美運動公園","YouBike2.0_榮華二明德路口","YouBike2.0_捷運明德站(1號出口)","YouBike2.0_文林建民路口","YouBike2.0_永欣綠地","YouBike2.0_關渡宮","YouBike2.0_關渡自然公園","YouBike2.0_關渡醫院","YouBike2.0_捷運忠義站(1號出口)","YouBike2.0_捷運關渡站(1號出口)","YouBike2.0_捷運關渡站(2號出口)","YouBike2.0_中央北路四段540巷口","YouBike2.0_大度立德路口","YouBike2.0_捷運復興崗站(1號出口)","YouBike2.0_捷運復興崗站旅客服務中心","YouBike2.0_豐年公園","YouBike2.0_國防大學政治作戰學院","YouBike2.0_秀山區民活動中心","YouBike2.0_大業大同街口","YouBike2.0_捷運新北投站","YouBike2.0_捷運北投站","YouBike2.0_捷運奇岩站(三合街)","YouBike2.0_八仙里辦公處","YouBike2.0_清江國小","YouBike2.0_大業路300巷口","YouBike2.0_立農公園","YouBike2.0_北投奇岩長青樂活大樓","YouBike2.0_捷運唭哩岸站(2號出口)","YouBike2.0_北投運動中心","YouBike2.0_陽明大學","YouBike2.0_捷運石牌站(2號出口)","YouBike2.0_台北護理大學","YouBike2.0_捷運石牌站(1號出口)","YouBike2.0_振興醫院","YouBike2.0_石牌國小","YouBike2.0_振興公園","YouBike2.0_立農國小","YouBike2.0_承德路七段280巷口","YouBike2.0_石牌區民活動中心","YouBike2.0_榮富公園","YouBike2.0_中正高中","YouBike2.0_立功立德路口","YouBike2.0_中央北路四段30巷口","YouBike2.0_陽明交大圖書館","YouBike2.0_捷運松山站(4號出口)","YouBike2.0_塔悠八德路口","YouBike2.0_南港公園(東新街)","YouBike2.0_捷運昆陽站(1號出口)","YouBike2.0_忠孝東路六段225巷口","YouBike2.0_捷運後山埤站(1號出口)","YouBike2.0_合樂公園","YouBike2.0_合心廣場","YouBike2.0_成德國中","YouBike2.0_玉成公園","YouBike2.0_研究院舊莊街口","YouBike2.0_中研院綜合體育館東側","YouBike2.0_國家生技園區","YouBike2.0_凌雲市場","YouBike2.0_捷運南港軟體園區(2號出口)","YouBike2.0_南港國小","YouBike2.0_興中立體停車場(興中路)","YouBike2.0_臺北市立圖書館南港分館","YouBike2.0_東陽公園","YouBike2.0_向陽南港路口","YouBike2.0_南港車站(忠孝東路七段415巷)","YouBike2.0_捷運南港站(1號出口)","YouBike2.0_東新國小.","YouBike2.0_黎忠區民活動中心","YouBike2.0_基隆路二段159巷口","YouBike2.0_嘉興街175巷口","YouBike2.0_和平東路三段631巷口","YouBike2.0_和平東路三段530巷口","YouBike2.0_景勤二號公園","YouBike2.0_臺北醫學大學","YouBike2.0_三興公園","YouBike2.0_松德站","YouBike2.0_捷運象山站(2號出口)","YouBike2.0_象山公園","YouBike2.0_松仁路253巷3弄","YouBike2.0_興雅國中","YouBike2.0_捷運象山站(1號出口)","YouBike2.0_松德路200巷","YouBike2.0_中全公園","YouBike2.0_信義運動中心","YouBike2.0_捷運台北101/世貿站(3號出口)","YouBike2.0_景新公園","YouBike2.0_三張犁","YouBike2.0_仁愛路四段496巷口","YouBike2.0_松山工農","YouBike2.0_松友公園","YouBike2.0_林口公園","YouBike2.0_松山家商","YouBike2.0_永春陂濕地公園","YouBike2.0_臺北市政府","YouBike2.0_松智松壽路口","YouBike2.0_市府松壽路口","YouBike2.0_市府松高路口","YouBike2.0_信義廣場(台北101)","YouBike2.0_捷運台北101/世貿站(5號出口)","YouBike2.0_春光公園","YouBike2.0_松仁路121巷口","YouBike2.0_福德國小","YouBike2.0_福德公園","YouBike2.0_興雅松仁路口","YouBike2.0_吳興公車總站","YouBike2.0_泰和公園","YouBike2.0_興雅國小(基隆路一段37巷)","YouBike2.0_雅祥公園(松信路50巷口)","YouBike2.0_松山車站","YouBike2.0_三興國小","YouBike2.0_德昌寶興街口(西北角)","YouBike2.0_國興中華路口","YouBike2.0_古亭國中","YouBike2.0_國興水源路口","YouBike2.0_青年公園高爾夫球場","YouBike2.0_國興青年路口","YouBike2.0_青年公園籃球場","YouBike2.0_新和國小","YouBike2.0_莒光郵局","YouBike2.0_莒光立體停車場","YouBike2.0_艋舺大道146巷口","YouBike2.0_東園國小","YouBike2.0_華中疏散門","YouBike2.0_萬華國中","YouBike2.0_華江高中","YouBike2.0_西園艋舺路口","YouBike2.0_雙園國中","YouBike2.0_華江國小","YouBike2.0_華江八號公園","YouBike2.0_環河南雙園街口","YouBike2.0_大理高中","YouBike2.0_糖廍文化園區","YouBike2.0_兩棵樹公園","YouBike2.0_萬華青年公宅","YouBike2.0_臺大水源舍區A棟","YouBike2.0_臺大卓越研究大樓","YouBike2.0_臺大水源修齊會館","YouBike2.0_臺大檔案展示館","YouBike2.0_臺大水源舍區B棟","YouBike2.0_臺大男八舍東側","YouBike2.0_臺大禮賢樓東南側","YouBike2.0_臺大農業陳列館北側","YouBike2.0_臺大管理學院二館北側","YouBike2.0_臺大土木系館","YouBike2.0_臺大大一女舍北側","YouBike2.0_臺大女九舍西南側","YouBike2.0_臺大小福樓東側","YouBike2.0_臺大立體機車停車場","YouBike2.0_臺大工綜館南側","YouBike2.0_臺大天文數學館南側","YouBike2.0_臺大心理系館南側","YouBike2.0_臺大樂學館東側","YouBike2.0_臺大農化新館西側","YouBike2.0_臺大五號館西側","YouBike2.0_臺大舊體育館西側","YouBike2.0_臺大共同教室北側","YouBike2.0_臺大共同教室東南側","YouBike2.0_臺大鹿鳴堂東側","YouBike2.0_臺大公館停車場西北側","YouBike2.0_臺大第二行政大樓南側","YouBike2.0_臺大明達館機車停車場","YouBike2.0_臺大二號館","YouBike2.0_臺大凝態館南側","YouBike2.0_臺大社科院西側","YouBike2.0_臺大社會系館南側","YouBike2.0_臺大思亮館東南側","YouBike2.0_臺大椰林小舖","YouBike2.0_臺大計資中心南側","YouBike2.0_臺大原分所北側","YouBike2.0_臺大校史館南側","YouBike2.0_臺大生命科學館西北側","YouBike2.0_臺大第一活動中心西南側","YouBike2.0_臺大博理館西側","YouBike2.0_臺大博雅館西側","YouBike2.0_臺大森林館北側","YouBike2.0_臺大一號館","YouBike2.0_臺大小小福西南側","YouBike2.0_臺大教研館北側","YouBike2.0_臺大四號館東北側","YouBike2.0_臺大新生教室南側","YouBike2.0_臺大鄭江樓北側","YouBike2.0_臺大電機二館東南側","YouBike2.0_臺大圖資系館北側","YouBike2.0_臺大總圖書館西南側","YouBike2.0_臺大黑森林西側","YouBike2.0_臺大獸醫館南側","YouBike2.0_臺大新體育館東南側"],["市政府","國父紀念館","市政府","台北101/世貿","象山","台北101/世貿","台北101/世貿","台北101/世貿","象山","台北101/世貿","信義安和","台北101/世貿","後山埤","中山國中","永春","松山機場","台北小巨蛋","象山","中山國中","松山","南港","大安森林公園","永春","昆陽","南港展覽館","松山","東門","科技大樓","台電大樓","六張犁","南京三民","行天宮","行天宮","科技大樓","東門","台電大樓","南港軟體園區","後山埤","南港","後山埤","南港","南港軟體園區","公館","南港軟體園區","忠孝新生","南港","忠孝敦化","松山機場","行天宮","松江南京","忠孝新生","大安森林公園","台北小巨蛋","善導寺","大安森林公園","善導寺","中山","行天宮","公館","古亭","忠孝復興","台大醫院","龍山寺","萬隆","台大醫院","小南門","萬隆","台北101/世貿","信義安和","松江南京","圓山","東門","信義安和","行天宮","南京三民","圓山","民權西路","龍山寺","台電大樓","西門","大安森林公園","龍山寺","信義安和","中山國中","大安","象山","中正紀念堂","龍山寺","圓山","北門","象山","景美","龍山寺","南京三民","劍潭","萬隆","雙連","忠孝新生","善導寺","台電大樓","龍山寺","萬隆","西門","龍山寺","小南門","圓山","中山國小","劍南路","忠孝復興","新北投","國父紀念館","芝山","台北車站","士林","北投","新北投","劍南路","龍山寺","南京復興","港墘","明德","石牌","龍山寺","六張犁","東湖","科技大樓","文德","中正紀念堂","西湖","公館","明德","芝山","石牌","石牌","復興崗","永春","北門","大橋頭","木柵","木柵","動物園","動物園","大橋頭","士林","劍潭","明德","唭哩岸","永春","大坪林","劍潭","民權西路","士林","港墘","東湖","西湖","東湖","西湖","北投","中山國小","麟光","奇岩","唭哩岸","七張","士林","古亭","小南門","南京三民","萬芳醫院","南京三民","松江南京","台北小巨蛋","南京復興","南京復興","三重國小","圓山","後山埤","文德","科技大樓","古亭","北門","大直","忠孝復興","小南門","國父紀念館","三和國中","內湖","大直","大湖公園","葫洲","南港展覽館","善導寺","東門","文德","松山","昆陽","關渡","中正紀念堂","芝山","萬芳醫院","辛亥","三民高中","龍山寺","復興崗","劍南路","內湖","大直","明德","松山","北門","大直","松山","市政府","龍山寺","大橋頭","麟光","民權西路","奇岩","劍潭","麟光","昆陽","港墘","萬芳社區","台北車站","文德","南京復興","明德","忠義","石牌","南京三民","關渡","萬芳醫院","港墘","松山","松江南京","永春","關渡","劍潭","忠孝復興","中山國中","劍南路","萬芳醫院","六張犁","小南門","忠孝復興","劍潭","科技大樓","芝山","關渡","國父紀念館","士林","龍山寺","北門","南京復興","文德","南京三民","萬芳社區","士林","復興崗","忠義","西湖","松山","南港","文德","芝山","松江南京","萬芳社區","芝山","文德","西門","台北101/世貿","西門","昆陽","南港","劍潭","松江南京","永春","關渡","士林","中正紀念堂","西湖","行天宮","善導寺","古亭","中山國小","松山","後山埤","公館","南京復興","科技大樓","萬隆","龍山寺","雙連","龍山寺","台北101/世貿","雙連","松山機場","葫洲","東門","內湖","古亭","忠孝敦化","南京三民","台北小巨蛋","中山國中","忠孝新生","信義安和","忠孝新生","台北小巨蛋","萬隆","中山國中","龍山寺","內湖","圓山","南京三民","龍山寺","中山國小","中山國小","劍潭","昆陽","市政府","中正紀念堂","松江南京","大直","圓山","圓山","中山","南京三民","信義安和","萬芳社區","民權西路","松山","後山埤","圓山","台北小巨蛋","芝山","明德","昆陽","忠孝復興","台大醫院","士林","西門","松山機場","圓山","科技大樓","台北車站","大橋頭","古亭","忠孝新生","南港展覽館","葫洲","象山","昆陽","南京三民","行天宮","石牌","古亭","大安","六張犁","石牌","文德","北投","芝山","景美","龍山寺","小南門","大橋頭","忠孝復興","葫洲","劍潭","行天宮","昆陽","港墘","後山埤","南京三民","文德","小南門","七張","南京復興","大坪林","行天宮","台北101/世貿","景美","後山埤","復興崗","景美","南京三民","大湖公園","永春","永春","南京三民","劍潭","芝山","台電大樓","六張犁","松江南京","葫洲","內湖","大橋頭","科技大樓","科技大樓","科技大樓","科技大樓","科技大樓","科技大樓","科技大樓","科技大樓","台電大樓","公館","公館","公館","台電大樓","科技大樓","公館","科技大樓","台電大樓","台電大樓","台電大樓","科技大樓","台電大樓","公館","公館","公館","公館","公館","公館","公館","公館","公館","公館","六張犁","科技大樓","科技大樓","公館","六張犁","科技大樓","科技大樓","科技大樓","科技大樓","台電大樓","台電大樓","科技大樓","科技大樓","科技大樓","科技大樓","台電大樓","六張犁","六張犁","麟光","六張犁","六張犁","麟光","六張犁","六張犁","六張犁","台電大樓","古亭","台電大樓","台電大樓","台電大樓","古亭","古亭","大安森林公園","大安森林公園","科技大樓","東門","東門","東門","東門","東門","六張犁","六張犁","六張犁","信義安和","信義安和","忠孝新生","忠孝新生","大安森林公園","大安森林公園","大安","忠孝新生","忠孝復興","大安","大安","大安","忠孝敦化","信義安和","信義安和","信義安和","忠孝新生","忠孝復興","大安森林公園","信義安和","信義安和","國父紀念館","大安森林公園","忠孝新生","大安","忠孝新生","忠孝復興","忠孝敦化","圓山","劍潭","劍潭","劍潭","劍潭","芝山","明德","明德","明德","明德","芝山","明德","明德","石牌","明德","劍潭","劍潭","芝山","芝山","芝山","芝山","芝山","劍潭","劍潭","劍潭","劍潭","劍潭","芝山","芝山","劍潭","劍潭","士林","士林","士林","劍潭","士林","芝山","芝山","士林","士林","士林","劍潭","士林","芝山","芝山","芝山","士林","劍南路","士林","士林","劍潭","劍潭","劍潭","三重國小","芝山","劍潭","三和國中","芝山","芝山","劍潭","劍南路","士林","士林","劍潭","關渡","三民高中","蘆洲","奇岩","三民高中","三和國中","芝山","萬隆","萬隆","萬隆","萬隆","萬隆","景美","景美","萬隆","萬隆","辛亥","萬隆","萬隆","萬隆","景美","木柵","萬芳社區","辛亥","萬隆","景美","七張","萬芳社區","萬芳社區","萬芳社區","公館","公館","公館","公館","古亭","古亭","台電大樓","台電大樓","古亭","古亭","台電大樓","台電大樓","古亭","古亭","古亭","古亭","古亭","中正紀念堂","中正紀念堂","古亭","中正紀念堂","中正紀念堂","中正紀念堂","中正紀念堂","中正紀念堂","小南門","小南門","小南門","龍山寺","小南門","小南門","台電大樓","小南門","小南門","台大醫院","西門","善導寺","善導寺","善導寺","台大醫院","台大醫院","東門","善導寺","小南門","小南門","西門","西門","小南門","小南門","台大醫院","忠孝新生","西門","北門","北門","台大醫院","公館","大直","劍潭","西湖","大直","大直","大直","劍南路","劍南路","劍南路","劍南路","大直","劍南路","西湖","西湖","西湖","劍南路","西湖","西湖","西湖","港墘","港墘","大湖公園","東湖","東湖","港墘","港墘","大湖公園","內湖","內湖","西湖","西湖","西湖","港墘","西湖","內湖","內湖","內湖","文德","文德","文德","文德","港墘","文德","松山","松山","松山","松山","松山","東湖","昆陽","昆陽","昆陽","昆陽","文德","文德","文德","文德","松山","松山","松山","文德","葫洲","葫洲","葫洲","葫洲","文德","文德","文德","文德","大湖公園","內湖","東湖","葫洲","大湖公園","港墘","唭哩岸","唭哩岸","明德","明德","明德","石牌","關渡","關渡","關渡","忠義","關渡","關渡","關渡","關渡","復興崗","復興崗","北投","復興崗","復興崗","新北投","新北投","北投","奇岩","奇岩","奇岩","北投","唭哩岸","奇岩","唭哩岸","唭哩岸","石牌","石牌","石牌","石牌","石牌","石牌","石牌","唭哩岸","唭哩岸","石牌","明德","明德","關渡","忠義","石牌","松山","松山","昆陽","昆陽","昆陽","後山埤","後山埤","後山埤","後山埤","後山埤","南港展覽館","南港","南港","南港","南港軟體園區","南港軟體園區","南港","南港","昆陽","昆陽","南港","南港","南港","麟光","六張犁","六張犁","麟光","麟光","六張犁","台北101/世貿","台北101/世貿","象山","象山","象山","象山","象山","象山","象山","永春","台北101/世貿","台北101/世貿","台北101/世貿","信義安和","國父紀念館","永春","象山","永春","永春","永春","市政府","台北101/世貿","台北101/世貿","市政府","台北101/世貿","台北101/世貿","後山埤","象山","後山埤","後山埤","市政府","象山","麟光","南京三民","松山","松山","信義安和","龍山寺","小南門","中正紀念堂","頂溪","小南門","小南門","頂溪","龍山寺","龍山寺","龍山寺","龍山寺","龍山寺","頂溪","龍山寺","龍山寺","龍山寺","龍山寺","龍山寺","龍山寺","龍山寺","龍山寺","龍山寺","龍山寺","頂溪","公館","公館","公館","公館","公館","科技大樓","公館","公館","公館","公館","公館","公館","公館","公館","公館","公館","公館","公館","公館","公館","公館","公館","公館","公館","公館","公館","科技大樓","公館","公館","科技大樓","科技大樓","科技大樓","公館","科技大樓","公館","公館","公館","公館","科技大樓","公館","公館","公館","公館","公館","公館","公館","科技大樓","科技大樓","公館","公館","科技大樓","公館","公館"]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th> <\/th>\n      <th>YouBike<\/th>\n      <th>MRT<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"pageLength":10,"order":[],"autoWidth":false,"orderClasses":false,"columnDefs":[{"orderable":false,"targets":0}]}},"evals":[],"jsHooks":[]}</script>
<p>Again, we must note that the result of function <code>st_nearest_feature()</code> retrieves is the “index” of nearest feature, not the simple feature itself. For instance, the first row of YouBike data is station “YouBike1.0_捷運市政府站(3號出口),” and the index of its nearest feature is 116, that is, the 116<sup>th</sup> row of MRT data (Taipei City Hall).</p>
</div>
<div id="convex-hull" class="section level2" number="5.14">
<h2><span class="header-section-number">5.14</span> Convex Hull</h2>
</div>
<div id="voronoi-polygon" class="section level2" number="5.15">
<h2><span class="header-section-number">5.15</span> Voronoi Polygon</h2>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="geographic-data.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "serif",
"size": 2
},
"edit": {
"link": "https://github.com/ChiaJung-Yeh/Spatial-Analysis/blob/master/04-Spatial-Operations.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["series.pdf"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
